-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
-- Generated on: 2023-03-16 12:07:10
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- OptimizeForHDL: on
-- TargetDirectory: C:\Users\John\Desktop\Honours_Project\helper
-- TestBenchStimulus: step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure      : Direct-Form FIR Polyphase Sample-Rate Converter
-- Interpolation Factor  : 1
-- Decimation Factor     : 10
-- Polyphase Length      : 240
-- Filter Length         : 240
-- Stable                : Yes
-- Linear Phase          : Yes (Type 1)
--
-- Arithmetic            : double
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    real; -- double
         filter_out                      :   OUT   real; -- double
         ce_in                           :   OUT   std_logic; 
         ce_out                          :   OUT   std_logic  
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF real; -- double
  -- Constants
  CONSTANT coeffphase1_1                  : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_2                  : real := -2.8150443134893359E-06; -- double
  CONSTANT coeffphase1_3                  : real := -6.6976238725875895E-06; -- double
  CONSTANT coeffphase1_4                  : real := -1.1304990269963141E-05; -- double
  CONSTANT coeffphase1_5                  : real := -1.6044314978571360E-05; -- double
  CONSTANT coeffphase1_6                  : real := -2.0107668908504811E-05; -- double
  CONSTANT coeffphase1_7                  : real := -2.2551548723864884E-05; -- double
  CONSTANT coeffphase1_8                  : real := -2.2417655357545307E-05; -- double
  CONSTANT coeffphase1_9                  : real := -1.8884484009097000E-05; -- double
  CONSTANT coeffphase1_10                 : real := -1.1432466271200507E-05; -- double
  CONSTANT coeffphase1_11                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_12                 : real := 1.4895245252218591E-05; -- double
  CONSTANT coeffphase1_13                 : real := 3.2095008337577838E-05; -- double
  CONSTANT coeffphase1_14                 : real := 4.9820225517987918E-05; -- double
  CONSTANT coeffphase1_15                 : real := 6.5785115051100965E-05; -- double
  CONSTANT coeffphase1_16                 : real := 7.7407541331296344E-05; -- double
  CONSTANT coeffphase1_17                 : real := 8.2104253823912543E-05; -- double
  CONSTANT coeffphase1_18                 : real := 7.7645572835330541E-05; -- double
  CONSTANT coeffphase1_19                 : real := 6.2531307977269570E-05; -- double
  CONSTANT coeffphase1_20                 : real := 3.6340120870154232E-05; -- double
  CONSTANT coeffphase1_21                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_22                 : real := -4.4070606517077606E-05; -- double
  CONSTANT coeffphase1_23                 : real := -9.1992441252299547E-05; -- double
  CONSTANT coeffphase1_24                 : real := -1.3865131496628788E-04; -- double
  CONSTANT coeffphase1_25                 : real := -1.7812378842843907E-04; -- double
  CONSTANT coeffphase1_26                 : real := -2.0428055285240439E-04; -- double
  CONSTANT coeffphase1_27                 : real := -2.1151874988768109E-04; -- double
  CONSTANT coeffphase1_28                 : real := -1.9555021117162184E-04; -- double
  CONSTANT coeffphase1_29                 : real := -1.5415423350615754E-04; -- double
  CONSTANT coeffphase1_30                 : real := -8.7794243989363754E-05; -- double
  CONSTANT coeffphase1_31                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_32                 : real := 1.0256790594364044E-04; -- double
  CONSTANT coeffphase1_33                 : real := 2.1042670346475102E-04; -- double
  CONSTANT coeffphase1_34                 : real := 3.1197016330681854E-04; -- double
  CONSTANT coeffphase1_35                 : real := 3.9452834212887124E-04; -- double
  CONSTANT coeffphase1_36                 : real := 4.4571081166024741E-04; -- double
  CONSTANT coeffphase1_37                 : real := 4.5491047167882788E-04; -- double
  CONSTANT coeffphase1_38                 : real := 4.1480885983109225E-04; -- double
  CONSTANT coeffphase1_39                 : real := 3.2270247585875563E-04; -- double
  CONSTANT coeffphase1_40                 : real := 1.8146749714553596E-04; -- double
  CONSTANT coeffphase1_41                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_42                 : real := -2.0698933341495155E-04; -- double
  CONSTANT coeffphase1_43                 : real := -4.1988547070270961E-04; -- double
  CONSTANT coeffphase1_44                 : real := -6.1576751176877582E-04; -- double
  CONSTANT coeffphase1_45                 : real := -7.7059530835929936E-04; -- double
  CONSTANT coeffphase1_46                 : real := -8.6180274791548600E-04; -- double
  CONSTANT coeffphase1_47                 : real := -8.7104673941122625E-04; -- double
  CONSTANT coeffphase1_48                 : real := -7.8681293323371363E-04; -- double
  CONSTANT coeffphase1_49                 : real := -6.0656076160268480E-04; -- double
  CONSTANT coeffphase1_50                 : real := -3.3810693938500329E-04; -- double
  CONSTANT coeffphase1_51                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_52                 : real := 3.7927350285030427E-04; -- double
  CONSTANT coeffphase1_53                 : real := 7.6329437485913372E-04; -- double
  CONSTANT coeffphase1_54                 : real := 1.1108373102628724E-03; -- double
  CONSTANT coeffphase1_55                 : real := 1.3798905245745504E-03; -- double
  CONSTANT coeffphase1_56                 : real := 1.5322143464772447E-03; -- double
  CONSTANT coeffphase1_57                 : real := 1.5379856988276951E-03; -- double
  CONSTANT coeffphase1_58                 : real := 1.3800177155234763E-03; -- double
  CONSTANT coeffphase1_59                 : real := 1.0570380058579536E-03; -- double
  CONSTANT coeffphase1_60                 : real := 5.8556108492878001E-04; -- double
  CONSTANT coeffphase1_61                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_62                 : real := -6.4917759672944615E-04; -- double
  CONSTANT coeffphase1_63                 : real := -1.2992459216626462E-03; -- double
  CONSTANT coeffphase1_64                 : real := -1.8807504058385085E-03; -- double
  CONSTANT coeffphase1_65                 : real := -2.3243371190692537E-03; -- double
  CONSTANT coeffphase1_66                 : real := -2.5682639904175543E-03; -- double
  CONSTANT coeffphase1_67                 : real := -2.5658408413689869E-03; -- double
  CONSTANT coeffphase1_68                 : real := -2.2919808744064647E-03; -- double
  CONSTANT coeffphase1_69                 : real := -1.7480656588507297E-03; -- double
  CONSTANT coeffphase1_70                 : real := -9.6443416645807867E-04; -- double
  CONSTANT coeffphase1_71                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_72                 : real := 1.0612340945903454E-03; -- double
  CONSTANT coeffphase1_73                 : real := 2.1166817264924782E-03; -- double
  CONSTANT coeffphase1_74                 : real := 3.0542832592820018E-03; -- double
  CONSTANT coeffphase1_75                 : real := 3.7634891815493260E-03; -- double
  CONSTANT coeffphase1_76                 : real := 4.1471187476899117E-03; -- double
  CONSTANT coeffphase1_77                 : real := 4.1329142567326201E-03; -- double
  CONSTANT coeffphase1_78                 : real := 3.6835396113406400E-03; -- double
  CONSTANT coeffphase1_79                 : real := 2.8038268898484147E-03; -- double
  CONSTANT coeffphase1_80                 : real := 1.5442609210198029E-03; -- double
  CONSTANT coeffphase1_81                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_82                 : real := -1.6948619659709831E-03; -- double
  CONSTANT coeffphase1_83                 : real := -3.3776154840431298E-03; -- double
  CONSTANT coeffphase1_84                 : real := -4.8711705413799714E-03; -- double
  CONSTANT coeffphase1_85                 : real := -6.0010788068776662E-03; -- double
  CONSTANT coeffphase1_86                 : real := -6.6138342553605893E-03; -- double
  CONSTANT coeffphase1_87                 : real := -6.5946878434032449E-03; -- double
  CONSTANT coeffphase1_88                 : real := -5.8831167309433404E-03; -- double
  CONSTANT coeffphase1_89                 : real := -4.4841751704463514E-03; -- double
  CONSTANT coeffphase1_90                 : real := -2.4742265994219981E-03; -- double
  CONSTANT coeffphase1_91                 : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_92                 : real := 2.7295047669241785E-03; -- double
  CONSTANT coeffphase1_93                 : real := 5.4580672264047140E-03; -- double
  CONSTANT coeffphase1_94                 : real := 7.9033579580103080E-03; -- double
  CONSTANT coeffphase1_95                 : real := 9.7825581636991031E-03; -- double
  CONSTANT coeffphase1_96                 : real := 1.0840381318230943E-02; -- double
  CONSTANT coeffphase1_97                 : real := 1.0877006554497207E-02; -- double
  CONSTANT coeffphase1_98                 : real := 9.7732642798801939E-03; -- double
  CONSTANT coeffphase1_99                 : real := 7.5104897250429506E-03; -- double
  CONSTANT coeffphase1_100                : real := 4.1827862769845169E-03; -- double
  CONSTANT coeffphase1_101                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_102                : real := -4.7195413599075689E-03; -- double
  CONSTANT coeffphase1_103                : real := -9.5665889624341766E-03; -- double
  CONSTANT coeffphase1_104                : real := -1.4067960771227194E-02; -- double
  CONSTANT coeffphase1_105                : real := -1.7721179958304981E-02; -- double
  CONSTANT coeffphase1_106                : real := -2.0034200470068875E-02; -- double
  CONSTANT coeffphase1_107                : real := -2.0567066295356227E-02; -- double
  CONSTANT coeffphase1_108                : real := -1.8972020184954679E-02; -- double
  CONSTANT coeffphase1_109                : real := -1.5028546890858729E-02; -- double
  CONSTANT coeffphase1_110                : real := -8.6701194720131738E-03; -- double
  CONSTANT coeffphase1_111                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_112                : real := 1.0705715087948866E-02; -- double
  CONSTANT coeffphase1_113                : real := 2.3008587891397470E-02; -- double
  CONSTANT coeffphase1_114                : real := 3.6331525716839785E-02; -- double
  CONSTANT coeffphase1_115                : real := 4.9994187915671576E-02; -- double
  CONSTANT coeffphase1_116                : real := 6.3257609665124753E-02; -- double
  CONSTANT coeffphase1_117                : real := 7.5374703493635523E-02; -- double
  CONSTANT coeffphase1_118                : real := 8.5642735226220831E-02; -- double
  CONSTANT coeffphase1_119                : real := 9.3453633434288683E-02; -- double
  CONSTANT coeffphase1_120                : real := 9.8338106184078192E-02; -- double
  CONSTANT coeffphase1_121                : real := 1.0000000000000001E-01; -- double
  CONSTANT coeffphase1_122                : real := 9.8338106184078192E-02; -- double
  CONSTANT coeffphase1_123                : real := 9.3453633434288683E-02; -- double
  CONSTANT coeffphase1_124                : real := 8.5642735226220831E-02; -- double
  CONSTANT coeffphase1_125                : real := 7.5374703493635523E-02; -- double
  CONSTANT coeffphase1_126                : real := 6.3257609665124753E-02; -- double
  CONSTANT coeffphase1_127                : real := 4.9994187915671576E-02; -- double
  CONSTANT coeffphase1_128                : real := 3.6331525716839785E-02; -- double
  CONSTANT coeffphase1_129                : real := 2.3008587891397470E-02; -- double
  CONSTANT coeffphase1_130                : real := 1.0705715087948866E-02; -- double
  CONSTANT coeffphase1_131                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_132                : real := -8.6701194720131738E-03; -- double
  CONSTANT coeffphase1_133                : real := -1.5028546890858729E-02; -- double
  CONSTANT coeffphase1_134                : real := -1.8972020184954679E-02; -- double
  CONSTANT coeffphase1_135                : real := -2.0567066295356227E-02; -- double
  CONSTANT coeffphase1_136                : real := -2.0034200470068875E-02; -- double
  CONSTANT coeffphase1_137                : real := -1.7721179958304981E-02; -- double
  CONSTANT coeffphase1_138                : real := -1.4067960771227194E-02; -- double
  CONSTANT coeffphase1_139                : real := -9.5665889624341766E-03; -- double
  CONSTANT coeffphase1_140                : real := -4.7195413599075689E-03; -- double
  CONSTANT coeffphase1_141                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_142                : real := 4.1827862769845169E-03; -- double
  CONSTANT coeffphase1_143                : real := 7.5104897250429506E-03; -- double
  CONSTANT coeffphase1_144                : real := 9.7732642798801939E-03; -- double
  CONSTANT coeffphase1_145                : real := 1.0877006554497207E-02; -- double
  CONSTANT coeffphase1_146                : real := 1.0840381318230943E-02; -- double
  CONSTANT coeffphase1_147                : real := 9.7825581636991031E-03; -- double
  CONSTANT coeffphase1_148                : real := 7.9033579580103080E-03; -- double
  CONSTANT coeffphase1_149                : real := 5.4580672264047140E-03; -- double
  CONSTANT coeffphase1_150                : real := 2.7295047669241785E-03; -- double
  CONSTANT coeffphase1_151                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_152                : real := -2.4742265994219981E-03; -- double
  CONSTANT coeffphase1_153                : real := -4.4841751704463514E-03; -- double
  CONSTANT coeffphase1_154                : real := -5.8831167309433404E-03; -- double
  CONSTANT coeffphase1_155                : real := -6.5946878434032449E-03; -- double
  CONSTANT coeffphase1_156                : real := -6.6138342553605893E-03; -- double
  CONSTANT coeffphase1_157                : real := -6.0010788068776662E-03; -- double
  CONSTANT coeffphase1_158                : real := -4.8711705413799714E-03; -- double
  CONSTANT coeffphase1_159                : real := -3.3776154840431298E-03; -- double
  CONSTANT coeffphase1_160                : real := -1.6948619659709831E-03; -- double
  CONSTANT coeffphase1_161                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_162                : real := 1.5442609210198029E-03; -- double
  CONSTANT coeffphase1_163                : real := 2.8038268898484147E-03; -- double
  CONSTANT coeffphase1_164                : real := 3.6835396113406400E-03; -- double
  CONSTANT coeffphase1_165                : real := 4.1329142567326201E-03; -- double
  CONSTANT coeffphase1_166                : real := 4.1471187476899117E-03; -- double
  CONSTANT coeffphase1_167                : real := 3.7634891815493260E-03; -- double
  CONSTANT coeffphase1_168                : real := 3.0542832592820018E-03; -- double
  CONSTANT coeffphase1_169                : real := 2.1166817264924782E-03; -- double
  CONSTANT coeffphase1_170                : real := 1.0612340945903454E-03; -- double
  CONSTANT coeffphase1_171                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_172                : real := -9.6443416645807867E-04; -- double
  CONSTANT coeffphase1_173                : real := -1.7480656588507297E-03; -- double
  CONSTANT coeffphase1_174                : real := -2.2919808744064647E-03; -- double
  CONSTANT coeffphase1_175                : real := -2.5658408413689869E-03; -- double
  CONSTANT coeffphase1_176                : real := -2.5682639904175543E-03; -- double
  CONSTANT coeffphase1_177                : real := -2.3243371190692537E-03; -- double
  CONSTANT coeffphase1_178                : real := -1.8807504058385085E-03; -- double
  CONSTANT coeffphase1_179                : real := -1.2992459216626462E-03; -- double
  CONSTANT coeffphase1_180                : real := -6.4917759672944615E-04; -- double
  CONSTANT coeffphase1_181                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_182                : real := 5.8556108492878001E-04; -- double
  CONSTANT coeffphase1_183                : real := 1.0570380058579536E-03; -- double
  CONSTANT coeffphase1_184                : real := 1.3800177155234763E-03; -- double
  CONSTANT coeffphase1_185                : real := 1.5379856988276951E-03; -- double
  CONSTANT coeffphase1_186                : real := 1.5322143464772447E-03; -- double
  CONSTANT coeffphase1_187                : real := 1.3798905245745504E-03; -- double
  CONSTANT coeffphase1_188                : real := 1.1108373102628724E-03; -- double
  CONSTANT coeffphase1_189                : real := 7.6329437485913372E-04; -- double
  CONSTANT coeffphase1_190                : real := 3.7927350285030427E-04; -- double
  CONSTANT coeffphase1_191                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_192                : real := -3.3810693938500329E-04; -- double
  CONSTANT coeffphase1_193                : real := -6.0656076160268480E-04; -- double
  CONSTANT coeffphase1_194                : real := -7.8681293323371363E-04; -- double
  CONSTANT coeffphase1_195                : real := -8.7104673941122625E-04; -- double
  CONSTANT coeffphase1_196                : real := -8.6180274791548600E-04; -- double
  CONSTANT coeffphase1_197                : real := -7.7059530835929936E-04; -- double
  CONSTANT coeffphase1_198                : real := -6.1576751176877582E-04; -- double
  CONSTANT coeffphase1_199                : real := -4.1988547070270961E-04; -- double
  CONSTANT coeffphase1_200                : real := -2.0698933341495155E-04; -- double
  CONSTANT coeffphase1_201                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_202                : real := 1.8146749714553596E-04; -- double
  CONSTANT coeffphase1_203                : real := 3.2270247585875563E-04; -- double
  CONSTANT coeffphase1_204                : real := 4.1480885983109225E-04; -- double
  CONSTANT coeffphase1_205                : real := 4.5491047167882788E-04; -- double
  CONSTANT coeffphase1_206                : real := 4.4571081166024741E-04; -- double
  CONSTANT coeffphase1_207                : real := 3.9452834212887124E-04; -- double
  CONSTANT coeffphase1_208                : real := 3.1197016330681854E-04; -- double
  CONSTANT coeffphase1_209                : real := 2.1042670346475102E-04; -- double
  CONSTANT coeffphase1_210                : real := 1.0256790594364044E-04; -- double
  CONSTANT coeffphase1_211                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_212                : real := -8.7794243989363754E-05; -- double
  CONSTANT coeffphase1_213                : real := -1.5415423350615754E-04; -- double
  CONSTANT coeffphase1_214                : real := -1.9555021117162184E-04; -- double
  CONSTANT coeffphase1_215                : real := -2.1151874988768109E-04; -- double
  CONSTANT coeffphase1_216                : real := -2.0428055285240439E-04; -- double
  CONSTANT coeffphase1_217                : real := -1.7812378842843907E-04; -- double
  CONSTANT coeffphase1_218                : real := -1.3865131496628788E-04; -- double
  CONSTANT coeffphase1_219                : real := -9.1992441252299547E-05; -- double
  CONSTANT coeffphase1_220                : real := -4.4070606517077606E-05; -- double
  CONSTANT coeffphase1_221                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_222                : real := 3.6340120870154232E-05; -- double
  CONSTANT coeffphase1_223                : real := 6.2531307977269570E-05; -- double
  CONSTANT coeffphase1_224                : real := 7.7645572835330541E-05; -- double
  CONSTANT coeffphase1_225                : real := 8.2104253823912543E-05; -- double
  CONSTANT coeffphase1_226                : real := 7.7407541331296344E-05; -- double
  CONSTANT coeffphase1_227                : real := 6.5785115051100965E-05; -- double
  CONSTANT coeffphase1_228                : real := 4.9820225517987918E-05; -- double
  CONSTANT coeffphase1_229                : real := 3.2095008337577838E-05; -- double
  CONSTANT coeffphase1_230                : real := 1.4895245252218591E-05; -- double
  CONSTANT coeffphase1_231                : real := 0.0000000000000000E+00; -- double
  CONSTANT coeffphase1_232                : real := -1.1432466271200507E-05; -- double
  CONSTANT coeffphase1_233                : real := -1.8884484009097000E-05; -- double
  CONSTANT coeffphase1_234                : real := -2.2417655357545307E-05; -- double
  CONSTANT coeffphase1_235                : real := -2.2551548723864884E-05; -- double
  CONSTANT coeffphase1_236                : real := -2.0107668908504811E-05; -- double
  CONSTANT coeffphase1_237                : real := -1.6044314978571360E-05; -- double
  CONSTANT coeffphase1_238                : real := -1.1304990269963141E-05; -- double
  CONSTANT coeffphase1_239                : real := -6.6976238725875895E-06; -- double
  CONSTANT coeffphase1_240                : real := -2.8150443134893359E-06; -- double

  -- Signals
  SIGNAL cur_count                        : unsigned(3 DOWNTO 0); -- ufix4
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL ce_out_reg                       : std_logic; -- boolean
  SIGNAL ce_in_reg                        : std_logic; -- boolean
  SIGNAL ce_out_phase                     : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 239) := (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0, 0.0); -- double
  SIGNAL product                          : real := 0.0; -- double
  SIGNAL product_1                        : real := 0.0; -- double
  SIGNAL product_2                        : real := 0.0; -- double
  SIGNAL product_3                        : real := 0.0; -- double
  SIGNAL product_4                        : real := 0.0; -- double
  SIGNAL product_5                        : real := 0.0; -- double
  SIGNAL product_6                        : real := 0.0; -- double
  SIGNAL product_7                        : real := 0.0; -- double
  SIGNAL product_8                        : real := 0.0; -- double
  SIGNAL product_9                        : real := 0.0; -- double
  SIGNAL product_10                       : real := 0.0; -- double
  SIGNAL product_11                       : real := 0.0; -- double
  SIGNAL product_12                       : real := 0.0; -- double
  SIGNAL product_13                       : real := 0.0; -- double
  SIGNAL product_14                       : real := 0.0; -- double
  SIGNAL product_15                       : real := 0.0; -- double
  SIGNAL product_16                       : real := 0.0; -- double
  SIGNAL product_17                       : real := 0.0; -- double
  SIGNAL product_18                       : real := 0.0; -- double
  SIGNAL product_19                       : real := 0.0; -- double
  SIGNAL product_20                       : real := 0.0; -- double
  SIGNAL product_21                       : real := 0.0; -- double
  SIGNAL product_22                       : real := 0.0; -- double
  SIGNAL product_23                       : real := 0.0; -- double
  SIGNAL product_24                       : real := 0.0; -- double
  SIGNAL product_25                       : real := 0.0; -- double
  SIGNAL product_26                       : real := 0.0; -- double
  SIGNAL product_27                       : real := 0.0; -- double
  SIGNAL product_28                       : real := 0.0; -- double
  SIGNAL product_29                       : real := 0.0; -- double
  SIGNAL product_30                       : real := 0.0; -- double
  SIGNAL product_31                       : real := 0.0; -- double
  SIGNAL product_32                       : real := 0.0; -- double
  SIGNAL product_33                       : real := 0.0; -- double
  SIGNAL product_34                       : real := 0.0; -- double
  SIGNAL product_35                       : real := 0.0; -- double
  SIGNAL product_36                       : real := 0.0; -- double
  SIGNAL product_37                       : real := 0.0; -- double
  SIGNAL product_38                       : real := 0.0; -- double
  SIGNAL product_39                       : real := 0.0; -- double
  SIGNAL product_40                       : real := 0.0; -- double
  SIGNAL product_41                       : real := 0.0; -- double
  SIGNAL product_42                       : real := 0.0; -- double
  SIGNAL product_43                       : real := 0.0; -- double
  SIGNAL product_44                       : real := 0.0; -- double
  SIGNAL product_45                       : real := 0.0; -- double
  SIGNAL product_46                       : real := 0.0; -- double
  SIGNAL product_47                       : real := 0.0; -- double
  SIGNAL product_48                       : real := 0.0; -- double
  SIGNAL product_49                       : real := 0.0; -- double
  SIGNAL product_50                       : real := 0.0; -- double
  SIGNAL product_51                       : real := 0.0; -- double
  SIGNAL product_52                       : real := 0.0; -- double
  SIGNAL product_53                       : real := 0.0; -- double
  SIGNAL product_54                       : real := 0.0; -- double
  SIGNAL product_55                       : real := 0.0; -- double
  SIGNAL product_56                       : real := 0.0; -- double
  SIGNAL product_57                       : real := 0.0; -- double
  SIGNAL product_58                       : real := 0.0; -- double
  SIGNAL product_59                       : real := 0.0; -- double
  SIGNAL product_60                       : real := 0.0; -- double
  SIGNAL product_61                       : real := 0.0; -- double
  SIGNAL product_62                       : real := 0.0; -- double
  SIGNAL product_63                       : real := 0.0; -- double
  SIGNAL product_64                       : real := 0.0; -- double
  SIGNAL product_65                       : real := 0.0; -- double
  SIGNAL product_66                       : real := 0.0; -- double
  SIGNAL product_67                       : real := 0.0; -- double
  SIGNAL product_68                       : real := 0.0; -- double
  SIGNAL product_69                       : real := 0.0; -- double
  SIGNAL product_70                       : real := 0.0; -- double
  SIGNAL product_71                       : real := 0.0; -- double
  SIGNAL product_72                       : real := 0.0; -- double
  SIGNAL product_73                       : real := 0.0; -- double
  SIGNAL product_74                       : real := 0.0; -- double
  SIGNAL product_75                       : real := 0.0; -- double
  SIGNAL product_76                       : real := 0.0; -- double
  SIGNAL product_77                       : real := 0.0; -- double
  SIGNAL product_78                       : real := 0.0; -- double
  SIGNAL product_79                       : real := 0.0; -- double
  SIGNAL product_80                       : real := 0.0; -- double
  SIGNAL product_81                       : real := 0.0; -- double
  SIGNAL product_82                       : real := 0.0; -- double
  SIGNAL product_83                       : real := 0.0; -- double
  SIGNAL product_84                       : real := 0.0; -- double
  SIGNAL product_85                       : real := 0.0; -- double
  SIGNAL product_86                       : real := 0.0; -- double
  SIGNAL product_87                       : real := 0.0; -- double
  SIGNAL product_88                       : real := 0.0; -- double
  SIGNAL product_89                       : real := 0.0; -- double
  SIGNAL product_90                       : real := 0.0; -- double
  SIGNAL product_91                       : real := 0.0; -- double
  SIGNAL product_92                       : real := 0.0; -- double
  SIGNAL product_93                       : real := 0.0; -- double
  SIGNAL product_94                       : real := 0.0; -- double
  SIGNAL product_95                       : real := 0.0; -- double
  SIGNAL product_96                       : real := 0.0; -- double
  SIGNAL product_97                       : real := 0.0; -- double
  SIGNAL product_98                       : real := 0.0; -- double
  SIGNAL product_99                       : real := 0.0; -- double
  SIGNAL product_100                      : real := 0.0; -- double
  SIGNAL product_101                      : real := 0.0; -- double
  SIGNAL product_102                      : real := 0.0; -- double
  SIGNAL product_103                      : real := 0.0; -- double
  SIGNAL product_104                      : real := 0.0; -- double
  SIGNAL product_105                      : real := 0.0; -- double
  SIGNAL product_106                      : real := 0.0; -- double
  SIGNAL product_107                      : real := 0.0; -- double
  SIGNAL product_108                      : real := 0.0; -- double
  SIGNAL product_109                      : real := 0.0; -- double
  SIGNAL product_110                      : real := 0.0; -- double
  SIGNAL product_111                      : real := 0.0; -- double
  SIGNAL product_112                      : real := 0.0; -- double
  SIGNAL product_113                      : real := 0.0; -- double
  SIGNAL product_114                      : real := 0.0; -- double
  SIGNAL product_115                      : real := 0.0; -- double
  SIGNAL product_116                      : real := 0.0; -- double
  SIGNAL product_117                      : real := 0.0; -- double
  SIGNAL product_118                      : real := 0.0; -- double
  SIGNAL product_119                      : real := 0.0; -- double
  SIGNAL product_120                      : real := 0.0; -- double
  SIGNAL product_121                      : real := 0.0; -- double
  SIGNAL product_122                      : real := 0.0; -- double
  SIGNAL product_123                      : real := 0.0; -- double
  SIGNAL product_124                      : real := 0.0; -- double
  SIGNAL product_125                      : real := 0.0; -- double
  SIGNAL product_126                      : real := 0.0; -- double
  SIGNAL product_127                      : real := 0.0; -- double
  SIGNAL product_128                      : real := 0.0; -- double
  SIGNAL product_129                      : real := 0.0; -- double
  SIGNAL product_130                      : real := 0.0; -- double
  SIGNAL product_131                      : real := 0.0; -- double
  SIGNAL product_132                      : real := 0.0; -- double
  SIGNAL product_133                      : real := 0.0; -- double
  SIGNAL product_134                      : real := 0.0; -- double
  SIGNAL product_135                      : real := 0.0; -- double
  SIGNAL product_136                      : real := 0.0; -- double
  SIGNAL product_137                      : real := 0.0; -- double
  SIGNAL product_138                      : real := 0.0; -- double
  SIGNAL product_139                      : real := 0.0; -- double
  SIGNAL product_140                      : real := 0.0; -- double
  SIGNAL product_141                      : real := 0.0; -- double
  SIGNAL product_142                      : real := 0.0; -- double
  SIGNAL product_143                      : real := 0.0; -- double
  SIGNAL product_144                      : real := 0.0; -- double
  SIGNAL product_145                      : real := 0.0; -- double
  SIGNAL product_146                      : real := 0.0; -- double
  SIGNAL product_147                      : real := 0.0; -- double
  SIGNAL product_148                      : real := 0.0; -- double
  SIGNAL product_149                      : real := 0.0; -- double
  SIGNAL product_150                      : real := 0.0; -- double
  SIGNAL product_151                      : real := 0.0; -- double
  SIGNAL product_152                      : real := 0.0; -- double
  SIGNAL product_153                      : real := 0.0; -- double
  SIGNAL product_154                      : real := 0.0; -- double
  SIGNAL product_155                      : real := 0.0; -- double
  SIGNAL product_156                      : real := 0.0; -- double
  SIGNAL product_157                      : real := 0.0; -- double
  SIGNAL product_158                      : real := 0.0; -- double
  SIGNAL product_159                      : real := 0.0; -- double
  SIGNAL product_160                      : real := 0.0; -- double
  SIGNAL product_161                      : real := 0.0; -- double
  SIGNAL product_162                      : real := 0.0; -- double
  SIGNAL product_163                      : real := 0.0; -- double
  SIGNAL product_164                      : real := 0.0; -- double
  SIGNAL product_165                      : real := 0.0; -- double
  SIGNAL product_166                      : real := 0.0; -- double
  SIGNAL product_167                      : real := 0.0; -- double
  SIGNAL product_168                      : real := 0.0; -- double
  SIGNAL product_169                      : real := 0.0; -- double
  SIGNAL product_170                      : real := 0.0; -- double
  SIGNAL product_171                      : real := 0.0; -- double
  SIGNAL product_172                      : real := 0.0; -- double
  SIGNAL product_173                      : real := 0.0; -- double
  SIGNAL product_174                      : real := 0.0; -- double
  SIGNAL product_175                      : real := 0.0; -- double
  SIGNAL product_176                      : real := 0.0; -- double
  SIGNAL product_177                      : real := 0.0; -- double
  SIGNAL product_178                      : real := 0.0; -- double
  SIGNAL product_179                      : real := 0.0; -- double
  SIGNAL product_180                      : real := 0.0; -- double
  SIGNAL product_181                      : real := 0.0; -- double
  SIGNAL product_182                      : real := 0.0; -- double
  SIGNAL product_183                      : real := 0.0; -- double
  SIGNAL product_184                      : real := 0.0; -- double
  SIGNAL product_185                      : real := 0.0; -- double
  SIGNAL product_186                      : real := 0.0; -- double
  SIGNAL product_187                      : real := 0.0; -- double
  SIGNAL product_188                      : real := 0.0; -- double
  SIGNAL product_189                      : real := 0.0; -- double
  SIGNAL product_190                      : real := 0.0; -- double
  SIGNAL product_191                      : real := 0.0; -- double
  SIGNAL product_192                      : real := 0.0; -- double
  SIGNAL product_193                      : real := 0.0; -- double
  SIGNAL product_194                      : real := 0.0; -- double
  SIGNAL product_195                      : real := 0.0; -- double
  SIGNAL product_196                      : real := 0.0; -- double
  SIGNAL product_197                      : real := 0.0; -- double
  SIGNAL product_198                      : real := 0.0; -- double
  SIGNAL product_199                      : real := 0.0; -- double
  SIGNAL product_200                      : real := 0.0; -- double
  SIGNAL product_201                      : real := 0.0; -- double
  SIGNAL product_202                      : real := 0.0; -- double
  SIGNAL product_203                      : real := 0.0; -- double
  SIGNAL product_204                      : real := 0.0; -- double
  SIGNAL product_205                      : real := 0.0; -- double
  SIGNAL product_206                      : real := 0.0; -- double
  SIGNAL product_207                      : real := 0.0; -- double
  SIGNAL product_208                      : real := 0.0; -- double
  SIGNAL product_209                      : real := 0.0; -- double
  SIGNAL product_210                      : real := 0.0; -- double
  SIGNAL product_211                      : real := 0.0; -- double
  SIGNAL product_212                      : real := 0.0; -- double
  SIGNAL product_213                      : real := 0.0; -- double
  SIGNAL product_214                      : real := 0.0; -- double
  SIGNAL product_215                      : real := 0.0; -- double
  SIGNAL product_216                      : real := 0.0; -- double
  SIGNAL fir_sum                          : real := 0.0; -- double
  SIGNAL sum_1                            : real := 0.0; -- double
  SIGNAL sum_2                            : real := 0.0; -- double
  SIGNAL sum_3                            : real := 0.0; -- double
  SIGNAL sum_4                            : real := 0.0; -- double
  SIGNAL sum_5                            : real := 0.0; -- double
  SIGNAL sum_6                            : real := 0.0; -- double
  SIGNAL sum_7                            : real := 0.0; -- double
  SIGNAL sum_8                            : real := 0.0; -- double
  SIGNAL sum_9                            : real := 0.0; -- double
  SIGNAL sum_10                           : real := 0.0; -- double
  SIGNAL sum_11                           : real := 0.0; -- double
  SIGNAL sum_12                           : real := 0.0; -- double
  SIGNAL sum_13                           : real := 0.0; -- double
  SIGNAL sum_14                           : real := 0.0; -- double
  SIGNAL sum_15                           : real := 0.0; -- double
  SIGNAL sum_16                           : real := 0.0; -- double
  SIGNAL sum_17                           : real := 0.0; -- double
  SIGNAL sum_18                           : real := 0.0; -- double
  SIGNAL sum_19                           : real := 0.0; -- double
  SIGNAL sum_20                           : real := 0.0; -- double
  SIGNAL sum_21                           : real := 0.0; -- double
  SIGNAL sum_22                           : real := 0.0; -- double
  SIGNAL sum_23                           : real := 0.0; -- double
  SIGNAL sum_24                           : real := 0.0; -- double
  SIGNAL sum_25                           : real := 0.0; -- double
  SIGNAL sum_26                           : real := 0.0; -- double
  SIGNAL sum_27                           : real := 0.0; -- double
  SIGNAL sum_28                           : real := 0.0; -- double
  SIGNAL sum_29                           : real := 0.0; -- double
  SIGNAL sum_30                           : real := 0.0; -- double
  SIGNAL sum_31                           : real := 0.0; -- double
  SIGNAL sum_32                           : real := 0.0; -- double
  SIGNAL sum_33                           : real := 0.0; -- double
  SIGNAL sum_34                           : real := 0.0; -- double
  SIGNAL sum_35                           : real := 0.0; -- double
  SIGNAL sum_36                           : real := 0.0; -- double
  SIGNAL sum_37                           : real := 0.0; -- double
  SIGNAL sum_38                           : real := 0.0; -- double
  SIGNAL sum_39                           : real := 0.0; -- double
  SIGNAL sum_40                           : real := 0.0; -- double
  SIGNAL sum_41                           : real := 0.0; -- double
  SIGNAL sum_42                           : real := 0.0; -- double
  SIGNAL sum_43                           : real := 0.0; -- double
  SIGNAL sum_44                           : real := 0.0; -- double
  SIGNAL sum_45                           : real := 0.0; -- double
  SIGNAL sum_46                           : real := 0.0; -- double
  SIGNAL sum_47                           : real := 0.0; -- double
  SIGNAL sum_48                           : real := 0.0; -- double
  SIGNAL sum_49                           : real := 0.0; -- double
  SIGNAL sum_50                           : real := 0.0; -- double
  SIGNAL sum_51                           : real := 0.0; -- double
  SIGNAL sum_52                           : real := 0.0; -- double
  SIGNAL sum_53                           : real := 0.0; -- double
  SIGNAL sum_54                           : real := 0.0; -- double
  SIGNAL sum_55                           : real := 0.0; -- double
  SIGNAL sum_56                           : real := 0.0; -- double
  SIGNAL sum_57                           : real := 0.0; -- double
  SIGNAL sum_58                           : real := 0.0; -- double
  SIGNAL sum_59                           : real := 0.0; -- double
  SIGNAL sum_60                           : real := 0.0; -- double
  SIGNAL sum_61                           : real := 0.0; -- double
  SIGNAL sum_62                           : real := 0.0; -- double
  SIGNAL sum_63                           : real := 0.0; -- double
  SIGNAL sum_64                           : real := 0.0; -- double
  SIGNAL sum_65                           : real := 0.0; -- double
  SIGNAL sum_66                           : real := 0.0; -- double
  SIGNAL sum_67                           : real := 0.0; -- double
  SIGNAL sum_68                           : real := 0.0; -- double
  SIGNAL sum_69                           : real := 0.0; -- double
  SIGNAL sum_70                           : real := 0.0; -- double
  SIGNAL sum_71                           : real := 0.0; -- double
  SIGNAL sum_72                           : real := 0.0; -- double
  SIGNAL sum_73                           : real := 0.0; -- double
  SIGNAL sum_74                           : real := 0.0; -- double
  SIGNAL sum_75                           : real := 0.0; -- double
  SIGNAL sum_76                           : real := 0.0; -- double
  SIGNAL sum_77                           : real := 0.0; -- double
  SIGNAL sum_78                           : real := 0.0; -- double
  SIGNAL sum_79                           : real := 0.0; -- double
  SIGNAL sum_80                           : real := 0.0; -- double
  SIGNAL sum_81                           : real := 0.0; -- double
  SIGNAL sum_82                           : real := 0.0; -- double
  SIGNAL sum_83                           : real := 0.0; -- double
  SIGNAL sum_84                           : real := 0.0; -- double
  SIGNAL sum_85                           : real := 0.0; -- double
  SIGNAL sum_86                           : real := 0.0; -- double
  SIGNAL sum_87                           : real := 0.0; -- double
  SIGNAL sum_88                           : real := 0.0; -- double
  SIGNAL sum_89                           : real := 0.0; -- double
  SIGNAL sum_90                           : real := 0.0; -- double
  SIGNAL sum_91                           : real := 0.0; -- double
  SIGNAL sum_92                           : real := 0.0; -- double
  SIGNAL sum_93                           : real := 0.0; -- double
  SIGNAL sum_94                           : real := 0.0; -- double
  SIGNAL sum_95                           : real := 0.0; -- double
  SIGNAL sum_96                           : real := 0.0; -- double
  SIGNAL sum_97                           : real := 0.0; -- double
  SIGNAL sum_98                           : real := 0.0; -- double
  SIGNAL sum_99                           : real := 0.0; -- double
  SIGNAL sum_100                          : real := 0.0; -- double
  SIGNAL sum_101                          : real := 0.0; -- double
  SIGNAL sum_102                          : real := 0.0; -- double
  SIGNAL sum_103                          : real := 0.0; -- double
  SIGNAL sum_104                          : real := 0.0; -- double
  SIGNAL sum_105                          : real := 0.0; -- double
  SIGNAL sum_106                          : real := 0.0; -- double
  SIGNAL sum_107                          : real := 0.0; -- double
  SIGNAL sum_108                          : real := 0.0; -- double
  SIGNAL sum_109                          : real := 0.0; -- double
  SIGNAL sum_110                          : real := 0.0; -- double
  SIGNAL sum_111                          : real := 0.0; -- double
  SIGNAL sum_112                          : real := 0.0; -- double
  SIGNAL sum_113                          : real := 0.0; -- double
  SIGNAL sum_114                          : real := 0.0; -- double
  SIGNAL sum_115                          : real := 0.0; -- double
  SIGNAL sum_116                          : real := 0.0; -- double
  SIGNAL sum_117                          : real := 0.0; -- double
  SIGNAL sum_118                          : real := 0.0; -- double
  SIGNAL sum_119                          : real := 0.0; -- double
  SIGNAL sum_120                          : real := 0.0; -- double
  SIGNAL sum_121                          : real := 0.0; -- double
  SIGNAL sum_122                          : real := 0.0; -- double
  SIGNAL sum_123                          : real := 0.0; -- double
  SIGNAL sum_124                          : real := 0.0; -- double
  SIGNAL sum_125                          : real := 0.0; -- double
  SIGNAL sum_126                          : real := 0.0; -- double
  SIGNAL sum_127                          : real := 0.0; -- double
  SIGNAL sum_128                          : real := 0.0; -- double
  SIGNAL sum_129                          : real := 0.0; -- double
  SIGNAL sum_130                          : real := 0.0; -- double
  SIGNAL sum_131                          : real := 0.0; -- double
  SIGNAL sum_132                          : real := 0.0; -- double
  SIGNAL sum_133                          : real := 0.0; -- double
  SIGNAL sum_134                          : real := 0.0; -- double
  SIGNAL sum_135                          : real := 0.0; -- double
  SIGNAL sum_136                          : real := 0.0; -- double
  SIGNAL sum_137                          : real := 0.0; -- double
  SIGNAL sum_138                          : real := 0.0; -- double
  SIGNAL sum_139                          : real := 0.0; -- double
  SIGNAL sum_140                          : real := 0.0; -- double
  SIGNAL sum_141                          : real := 0.0; -- double
  SIGNAL sum_142                          : real := 0.0; -- double
  SIGNAL sum_143                          : real := 0.0; -- double
  SIGNAL sum_144                          : real := 0.0; -- double
  SIGNAL sum_145                          : real := 0.0; -- double
  SIGNAL sum_146                          : real := 0.0; -- double
  SIGNAL sum_147                          : real := 0.0; -- double
  SIGNAL sum_148                          : real := 0.0; -- double
  SIGNAL sum_149                          : real := 0.0; -- double
  SIGNAL sum_150                          : real := 0.0; -- double
  SIGNAL sum_151                          : real := 0.0; -- double
  SIGNAL sum_152                          : real := 0.0; -- double
  SIGNAL sum_153                          : real := 0.0; -- double
  SIGNAL sum_154                          : real := 0.0; -- double
  SIGNAL sum_155                          : real := 0.0; -- double
  SIGNAL sum_156                          : real := 0.0; -- double
  SIGNAL sum_157                          : real := 0.0; -- double
  SIGNAL sum_158                          : real := 0.0; -- double
  SIGNAL sum_159                          : real := 0.0; -- double
  SIGNAL sum_160                          : real := 0.0; -- double
  SIGNAL sum_161                          : real := 0.0; -- double
  SIGNAL sum_162                          : real := 0.0; -- double
  SIGNAL sum_163                          : real := 0.0; -- double
  SIGNAL sum_164                          : real := 0.0; -- double
  SIGNAL sum_165                          : real := 0.0; -- double
  SIGNAL sum_166                          : real := 0.0; -- double
  SIGNAL sum_167                          : real := 0.0; -- double
  SIGNAL sum_168                          : real := 0.0; -- double
  SIGNAL sum_169                          : real := 0.0; -- double
  SIGNAL sum_170                          : real := 0.0; -- double
  SIGNAL sum_171                          : real := 0.0; -- double
  SIGNAL sum_172                          : real := 0.0; -- double
  SIGNAL sum_173                          : real := 0.0; -- double
  SIGNAL sum_174                          : real := 0.0; -- double
  SIGNAL sum_175                          : real := 0.0; -- double
  SIGNAL sum_176                          : real := 0.0; -- double
  SIGNAL sum_177                          : real := 0.0; -- double
  SIGNAL sum_178                          : real := 0.0; -- double
  SIGNAL sum_179                          : real := 0.0; -- double
  SIGNAL sum_180                          : real := 0.0; -- double
  SIGNAL sum_181                          : real := 0.0; -- double
  SIGNAL sum_182                          : real := 0.0; -- double
  SIGNAL sum_183                          : real := 0.0; -- double
  SIGNAL sum_184                          : real := 0.0; -- double
  SIGNAL sum_185                          : real := 0.0; -- double
  SIGNAL sum_186                          : real := 0.0; -- double
  SIGNAL sum_187                          : real := 0.0; -- double
  SIGNAL sum_188                          : real := 0.0; -- double
  SIGNAL sum_189                          : real := 0.0; -- double
  SIGNAL sum_190                          : real := 0.0; -- double
  SIGNAL sum_191                          : real := 0.0; -- double
  SIGNAL sum_192                          : real := 0.0; -- double
  SIGNAL sum_193                          : real := 0.0; -- double
  SIGNAL sum_194                          : real := 0.0; -- double
  SIGNAL sum_195                          : real := 0.0; -- double
  SIGNAL sum_196                          : real := 0.0; -- double
  SIGNAL sum_197                          : real := 0.0; -- double
  SIGNAL sum_198                          : real := 0.0; -- double
  SIGNAL sum_199                          : real := 0.0; -- double
  SIGNAL sum_200                          : real := 0.0; -- double
  SIGNAL sum_201                          : real := 0.0; -- double
  SIGNAL sum_202                          : real := 0.0; -- double
  SIGNAL sum_203                          : real := 0.0; -- double
  SIGNAL sum_204                          : real := 0.0; -- double
  SIGNAL sum_205                          : real := 0.0; -- double
  SIGNAL sum_206                          : real := 0.0; -- double
  SIGNAL sum_207                          : real := 0.0; -- double
  SIGNAL sum_208                          : real := 0.0; -- double
  SIGNAL sum_209                          : real := 0.0; -- double
  SIGNAL sum_210                          : real := 0.0; -- double
  SIGNAL sum_211                          : real := 0.0; -- double
  SIGNAL sum_212                          : real := 0.0; -- double
  SIGNAL sum_213                          : real := 0.0; -- double
  SIGNAL sum_214                          : real := 0.0; -- double
  SIGNAL sum_215                          : real := 0.0; -- double
  SIGNAL output_register                  : real := 0.0; -- double


BEGIN

  -- Block Statements
  --   ------------------ CE Output Generation ------------------

  ce_output : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(0, 4);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count >= to_unsigned(9, 4) THEN
          cur_count <= to_unsigned(0, 4);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 4);
        END IF;
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_1 <= '1' WHEN cur_count = to_unsigned(1, 4) AND clk_enable = '1' ELSE '0';

  --   ------------------ CE Output Register ------------------

  ce_out_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ce_out_reg <= '0';
    ELSIF clk'event AND clk = '1' THEN
      ce_out_reg <= phase_1;
      
    END IF; 
  END PROCESS ce_out_delay_process;

  --   ------------------ CE Input Register ------------------

  ce_input_register : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ce_in_reg <= '0';
    ELSIF clk'event AND clk = '1' THEN
      ce_in_reg <= clk_enable;
      
    END IF; 
  END PROCESS ce_input_register;

  ce_out_phase <=  ce_out_reg AND clk_enable;

  --   ---------------- Delay Registers ----------------

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 239) <= (OTHERS => 0.0000000000000000E+00);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= filter_in;
        delay_pipeline(1 TO 239) <= delay_pipeline(0 TO 238);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  product <= delay_pipeline(239) * coeffphase1_240;

  product_1 <= delay_pipeline(238) * coeffphase1_239;

  product_2 <= delay_pipeline(237) * coeffphase1_238;

  product_3 <= delay_pipeline(236) * coeffphase1_237;

  product_4 <= delay_pipeline(235) * coeffphase1_236;

  product_5 <= delay_pipeline(234) * coeffphase1_235;

  product_6 <= delay_pipeline(233) * coeffphase1_234;

  product_7 <= delay_pipeline(232) * coeffphase1_233;

  product_8 <= delay_pipeline(231) * coeffphase1_232;

  product_9 <= delay_pipeline(229) * coeffphase1_230;

  product_10 <= delay_pipeline(228) * coeffphase1_229;

  product_11 <= delay_pipeline(227) * coeffphase1_228;

  product_12 <= delay_pipeline(226) * coeffphase1_227;

  product_13 <= delay_pipeline(225) * coeffphase1_226;

  product_14 <= delay_pipeline(224) * coeffphase1_225;

  product_15 <= delay_pipeline(223) * coeffphase1_224;

  product_16 <= delay_pipeline(222) * coeffphase1_223;

  product_17 <= delay_pipeline(221) * coeffphase1_222;

  product_18 <= delay_pipeline(219) * coeffphase1_220;

  product_19 <= delay_pipeline(218) * coeffphase1_219;

  product_20 <= delay_pipeline(217) * coeffphase1_218;

  product_21 <= delay_pipeline(216) * coeffphase1_217;

  product_22 <= delay_pipeline(215) * coeffphase1_216;

  product_23 <= delay_pipeline(214) * coeffphase1_215;

  product_24 <= delay_pipeline(213) * coeffphase1_214;

  product_25 <= delay_pipeline(212) * coeffphase1_213;

  product_26 <= delay_pipeline(211) * coeffphase1_212;

  product_27 <= delay_pipeline(209) * coeffphase1_210;

  product_28 <= delay_pipeline(208) * coeffphase1_209;

  product_29 <= delay_pipeline(207) * coeffphase1_208;

  product_30 <= delay_pipeline(206) * coeffphase1_207;

  product_31 <= delay_pipeline(205) * coeffphase1_206;

  product_32 <= delay_pipeline(204) * coeffphase1_205;

  product_33 <= delay_pipeline(203) * coeffphase1_204;

  product_34 <= delay_pipeline(202) * coeffphase1_203;

  product_35 <= delay_pipeline(201) * coeffphase1_202;

  product_36 <= delay_pipeline(199) * coeffphase1_200;

  product_37 <= delay_pipeline(198) * coeffphase1_199;

  product_38 <= delay_pipeline(197) * coeffphase1_198;

  product_39 <= delay_pipeline(196) * coeffphase1_197;

  product_40 <= delay_pipeline(195) * coeffphase1_196;

  product_41 <= delay_pipeline(194) * coeffphase1_195;

  product_42 <= delay_pipeline(193) * coeffphase1_194;

  product_43 <= delay_pipeline(192) * coeffphase1_193;

  product_44 <= delay_pipeline(191) * coeffphase1_192;

  product_45 <= delay_pipeline(189) * coeffphase1_190;

  product_46 <= delay_pipeline(188) * coeffphase1_189;

  product_47 <= delay_pipeline(187) * coeffphase1_188;

  product_48 <= delay_pipeline(186) * coeffphase1_187;

  product_49 <= delay_pipeline(185) * coeffphase1_186;

  product_50 <= delay_pipeline(184) * coeffphase1_185;

  product_51 <= delay_pipeline(183) * coeffphase1_184;

  product_52 <= delay_pipeline(182) * coeffphase1_183;

  product_53 <= delay_pipeline(181) * coeffphase1_182;

  product_54 <= delay_pipeline(179) * coeffphase1_180;

  product_55 <= delay_pipeline(178) * coeffphase1_179;

  product_56 <= delay_pipeline(177) * coeffphase1_178;

  product_57 <= delay_pipeline(176) * coeffphase1_177;

  product_58 <= delay_pipeline(175) * coeffphase1_176;

  product_59 <= delay_pipeline(174) * coeffphase1_175;

  product_60 <= delay_pipeline(173) * coeffphase1_174;

  product_61 <= delay_pipeline(172) * coeffphase1_173;

  product_62 <= delay_pipeline(171) * coeffphase1_172;

  product_63 <= delay_pipeline(169) * coeffphase1_170;

  product_64 <= delay_pipeline(168) * coeffphase1_169;

  product_65 <= delay_pipeline(167) * coeffphase1_168;

  product_66 <= delay_pipeline(166) * coeffphase1_167;

  product_67 <= delay_pipeline(165) * coeffphase1_166;

  product_68 <= delay_pipeline(164) * coeffphase1_165;

  product_69 <= delay_pipeline(163) * coeffphase1_164;

  product_70 <= delay_pipeline(162) * coeffphase1_163;

  product_71 <= delay_pipeline(161) * coeffphase1_162;

  product_72 <= delay_pipeline(159) * coeffphase1_160;

  product_73 <= delay_pipeline(158) * coeffphase1_159;

  product_74 <= delay_pipeline(157) * coeffphase1_158;

  product_75 <= delay_pipeline(156) * coeffphase1_157;

  product_76 <= delay_pipeline(155) * coeffphase1_156;

  product_77 <= delay_pipeline(154) * coeffphase1_155;

  product_78 <= delay_pipeline(153) * coeffphase1_154;

  product_79 <= delay_pipeline(152) * coeffphase1_153;

  product_80 <= delay_pipeline(151) * coeffphase1_152;

  product_81 <= delay_pipeline(149) * coeffphase1_150;

  product_82 <= delay_pipeline(148) * coeffphase1_149;

  product_83 <= delay_pipeline(147) * coeffphase1_148;

  product_84 <= delay_pipeline(146) * coeffphase1_147;

  product_85 <= delay_pipeline(145) * coeffphase1_146;

  product_86 <= delay_pipeline(144) * coeffphase1_145;

  product_87 <= delay_pipeline(143) * coeffphase1_144;

  product_88 <= delay_pipeline(142) * coeffphase1_143;

  product_89 <= delay_pipeline(141) * coeffphase1_142;

  product_90 <= delay_pipeline(139) * coeffphase1_140;

  product_91 <= delay_pipeline(138) * coeffphase1_139;

  product_92 <= delay_pipeline(137) * coeffphase1_138;

  product_93 <= delay_pipeline(136) * coeffphase1_137;

  product_94 <= delay_pipeline(135) * coeffphase1_136;

  product_95 <= delay_pipeline(134) * coeffphase1_135;

  product_96 <= delay_pipeline(133) * coeffphase1_134;

  product_97 <= delay_pipeline(132) * coeffphase1_133;

  product_98 <= delay_pipeline(131) * coeffphase1_132;

  product_99 <= delay_pipeline(129) * coeffphase1_130;

  product_100 <= delay_pipeline(128) * coeffphase1_129;

  product_101 <= delay_pipeline(127) * coeffphase1_128;

  product_102 <= delay_pipeline(126) * coeffphase1_127;

  product_103 <= delay_pipeline(125) * coeffphase1_126;

  product_104 <= delay_pipeline(124) * coeffphase1_125;

  product_105 <= delay_pipeline(123) * coeffphase1_124;

  product_106 <= delay_pipeline(122) * coeffphase1_123;

  product_107 <= delay_pipeline(121) * coeffphase1_122;

  product_108 <= delay_pipeline(120) * coeffphase1_121;

  product_109 <= delay_pipeline(119) * coeffphase1_120;

  product_110 <= delay_pipeline(118) * coeffphase1_119;

  product_111 <= delay_pipeline(117) * coeffphase1_118;

  product_112 <= delay_pipeline(116) * coeffphase1_117;

  product_113 <= delay_pipeline(115) * coeffphase1_116;

  product_114 <= delay_pipeline(114) * coeffphase1_115;

  product_115 <= delay_pipeline(113) * coeffphase1_114;

  product_116 <= delay_pipeline(112) * coeffphase1_113;

  product_117 <= delay_pipeline(111) * coeffphase1_112;

  product_118 <= delay_pipeline(109) * coeffphase1_110;

  product_119 <= delay_pipeline(108) * coeffphase1_109;

  product_120 <= delay_pipeline(107) * coeffphase1_108;

  product_121 <= delay_pipeline(106) * coeffphase1_107;

  product_122 <= delay_pipeline(105) * coeffphase1_106;

  product_123 <= delay_pipeline(104) * coeffphase1_105;

  product_124 <= delay_pipeline(103) * coeffphase1_104;

  product_125 <= delay_pipeline(102) * coeffphase1_103;

  product_126 <= delay_pipeline(101) * coeffphase1_102;

  product_127 <= delay_pipeline(99) * coeffphase1_100;

  product_128 <= delay_pipeline(98) * coeffphase1_99;

  product_129 <= delay_pipeline(97) * coeffphase1_98;

  product_130 <= delay_pipeline(96) * coeffphase1_97;

  product_131 <= delay_pipeline(95) * coeffphase1_96;

  product_132 <= delay_pipeline(94) * coeffphase1_95;

  product_133 <= delay_pipeline(93) * coeffphase1_94;

  product_134 <= delay_pipeline(92) * coeffphase1_93;

  product_135 <= delay_pipeline(91) * coeffphase1_92;

  product_136 <= delay_pipeline(89) * coeffphase1_90;

  product_137 <= delay_pipeline(88) * coeffphase1_89;

  product_138 <= delay_pipeline(87) * coeffphase1_88;

  product_139 <= delay_pipeline(86) * coeffphase1_87;

  product_140 <= delay_pipeline(85) * coeffphase1_86;

  product_141 <= delay_pipeline(84) * coeffphase1_85;

  product_142 <= delay_pipeline(83) * coeffphase1_84;

  product_143 <= delay_pipeline(82) * coeffphase1_83;

  product_144 <= delay_pipeline(81) * coeffphase1_82;

  product_145 <= delay_pipeline(79) * coeffphase1_80;

  product_146 <= delay_pipeline(78) * coeffphase1_79;

  product_147 <= delay_pipeline(77) * coeffphase1_78;

  product_148 <= delay_pipeline(76) * coeffphase1_77;

  product_149 <= delay_pipeline(75) * coeffphase1_76;

  product_150 <= delay_pipeline(74) * coeffphase1_75;

  product_151 <= delay_pipeline(73) * coeffphase1_74;

  product_152 <= delay_pipeline(72) * coeffphase1_73;

  product_153 <= delay_pipeline(71) * coeffphase1_72;

  product_154 <= delay_pipeline(69) * coeffphase1_70;

  product_155 <= delay_pipeline(68) * coeffphase1_69;

  product_156 <= delay_pipeline(67) * coeffphase1_68;

  product_157 <= delay_pipeline(66) * coeffphase1_67;

  product_158 <= delay_pipeline(65) * coeffphase1_66;

  product_159 <= delay_pipeline(64) * coeffphase1_65;

  product_160 <= delay_pipeline(63) * coeffphase1_64;

  product_161 <= delay_pipeline(62) * coeffphase1_63;

  product_162 <= delay_pipeline(61) * coeffphase1_62;

  product_163 <= delay_pipeline(59) * coeffphase1_60;

  product_164 <= delay_pipeline(58) * coeffphase1_59;

  product_165 <= delay_pipeline(57) * coeffphase1_58;

  product_166 <= delay_pipeline(56) * coeffphase1_57;

  product_167 <= delay_pipeline(55) * coeffphase1_56;

  product_168 <= delay_pipeline(54) * coeffphase1_55;

  product_169 <= delay_pipeline(53) * coeffphase1_54;

  product_170 <= delay_pipeline(52) * coeffphase1_53;

  product_171 <= delay_pipeline(51) * coeffphase1_52;

  product_172 <= delay_pipeline(49) * coeffphase1_50;

  product_173 <= delay_pipeline(48) * coeffphase1_49;

  product_174 <= delay_pipeline(47) * coeffphase1_48;

  product_175 <= delay_pipeline(46) * coeffphase1_47;

  product_176 <= delay_pipeline(45) * coeffphase1_46;

  product_177 <= delay_pipeline(44) * coeffphase1_45;

  product_178 <= delay_pipeline(43) * coeffphase1_44;

  product_179 <= delay_pipeline(42) * coeffphase1_43;

  product_180 <= delay_pipeline(41) * coeffphase1_42;

  product_181 <= delay_pipeline(39) * coeffphase1_40;

  product_182 <= delay_pipeline(38) * coeffphase1_39;

  product_183 <= delay_pipeline(37) * coeffphase1_38;

  product_184 <= delay_pipeline(36) * coeffphase1_37;

  product_185 <= delay_pipeline(35) * coeffphase1_36;

  product_186 <= delay_pipeline(34) * coeffphase1_35;

  product_187 <= delay_pipeline(33) * coeffphase1_34;

  product_188 <= delay_pipeline(32) * coeffphase1_33;

  product_189 <= delay_pipeline(31) * coeffphase1_32;

  product_190 <= delay_pipeline(29) * coeffphase1_30;

  product_191 <= delay_pipeline(28) * coeffphase1_29;

  product_192 <= delay_pipeline(27) * coeffphase1_28;

  product_193 <= delay_pipeline(26) * coeffphase1_27;

  product_194 <= delay_pipeline(25) * coeffphase1_26;

  product_195 <= delay_pipeline(24) * coeffphase1_25;

  product_196 <= delay_pipeline(23) * coeffphase1_24;

  product_197 <= delay_pipeline(22) * coeffphase1_23;

  product_198 <= delay_pipeline(21) * coeffphase1_22;

  product_199 <= delay_pipeline(19) * coeffphase1_20;

  product_200 <= delay_pipeline(18) * coeffphase1_19;

  product_201 <= delay_pipeline(17) * coeffphase1_18;

  product_202 <= delay_pipeline(16) * coeffphase1_17;

  product_203 <= delay_pipeline(15) * coeffphase1_16;

  product_204 <= delay_pipeline(14) * coeffphase1_15;

  product_205 <= delay_pipeline(13) * coeffphase1_14;

  product_206 <= delay_pipeline(12) * coeffphase1_13;

  product_207 <= delay_pipeline(11) * coeffphase1_12;

  product_208 <= delay_pipeline(9) * coeffphase1_10;

  product_209 <= delay_pipeline(8) * coeffphase1_9;

  product_210 <= delay_pipeline(7) * coeffphase1_8;

  product_211 <= delay_pipeline(6) * coeffphase1_7;

  product_212 <= delay_pipeline(5) * coeffphase1_6;

  product_213 <= delay_pipeline(4) * coeffphase1_5;

  product_214 <= delay_pipeline(3) * coeffphase1_4;

  product_215 <= delay_pipeline(2) * coeffphase1_3;

  product_216 <= delay_pipeline(1) * coeffphase1_2;

  sum_1 <= product_216 + product_215;

  sum_2 <= sum_1 + product_214;

  sum_3 <= sum_2 + product_213;

  sum_4 <= sum_3 + product_212;

  sum_5 <= sum_4 + product_211;

  sum_6 <= sum_5 + product_210;

  sum_7 <= sum_6 + product_209;

  sum_8 <= sum_7 + product_208;

  sum_9 <= sum_8 + product_207;

  sum_10 <= sum_9 + product_206;

  sum_11 <= sum_10 + product_205;

  sum_12 <= sum_11 + product_204;

  sum_13 <= sum_12 + product_203;

  sum_14 <= sum_13 + product_202;

  sum_15 <= sum_14 + product_201;

  sum_16 <= sum_15 + product_200;

  sum_17 <= sum_16 + product_199;

  sum_18 <= sum_17 + product_198;

  sum_19 <= sum_18 + product_197;

  sum_20 <= sum_19 + product_196;

  sum_21 <= sum_20 + product_195;

  sum_22 <= sum_21 + product_194;

  sum_23 <= sum_22 + product_193;

  sum_24 <= sum_23 + product_192;

  sum_25 <= sum_24 + product_191;

  sum_26 <= sum_25 + product_190;

  sum_27 <= sum_26 + product_189;

  sum_28 <= sum_27 + product_188;

  sum_29 <= sum_28 + product_187;

  sum_30 <= sum_29 + product_186;

  sum_31 <= sum_30 + product_185;

  sum_32 <= sum_31 + product_184;

  sum_33 <= sum_32 + product_183;

  sum_34 <= sum_33 + product_182;

  sum_35 <= sum_34 + product_181;

  sum_36 <= sum_35 + product_180;

  sum_37 <= sum_36 + product_179;

  sum_38 <= sum_37 + product_178;

  sum_39 <= sum_38 + product_177;

  sum_40 <= sum_39 + product_176;

  sum_41 <= sum_40 + product_175;

  sum_42 <= sum_41 + product_174;

  sum_43 <= sum_42 + product_173;

  sum_44 <= sum_43 + product_172;

  sum_45 <= sum_44 + product_171;

  sum_46 <= sum_45 + product_170;

  sum_47 <= sum_46 + product_169;

  sum_48 <= sum_47 + product_168;

  sum_49 <= sum_48 + product_167;

  sum_50 <= sum_49 + product_166;

  sum_51 <= sum_50 + product_165;

  sum_52 <= sum_51 + product_164;

  sum_53 <= sum_52 + product_163;

  sum_54 <= sum_53 + product_162;

  sum_55 <= sum_54 + product_161;

  sum_56 <= sum_55 + product_160;

  sum_57 <= sum_56 + product_159;

  sum_58 <= sum_57 + product_158;

  sum_59 <= sum_58 + product_157;

  sum_60 <= sum_59 + product_156;

  sum_61 <= sum_60 + product_155;

  sum_62 <= sum_61 + product_154;

  sum_63 <= sum_62 + product_153;

  sum_64 <= sum_63 + product_152;

  sum_65 <= sum_64 + product_151;

  sum_66 <= sum_65 + product_150;

  sum_67 <= sum_66 + product_149;

  sum_68 <= sum_67 + product_148;

  sum_69 <= sum_68 + product_147;

  sum_70 <= sum_69 + product_146;

  sum_71 <= sum_70 + product_145;

  sum_72 <= sum_71 + product_144;

  sum_73 <= sum_72 + product_143;

  sum_74 <= sum_73 + product_142;

  sum_75 <= sum_74 + product_141;

  sum_76 <= sum_75 + product_140;

  sum_77 <= sum_76 + product_139;

  sum_78 <= sum_77 + product_138;

  sum_79 <= sum_78 + product_137;

  sum_80 <= sum_79 + product_136;

  sum_81 <= sum_80 + product_135;

  sum_82 <= sum_81 + product_134;

  sum_83 <= sum_82 + product_133;

  sum_84 <= sum_83 + product_132;

  sum_85 <= sum_84 + product_131;

  sum_86 <= sum_85 + product_130;

  sum_87 <= sum_86 + product_129;

  sum_88 <= sum_87 + product_128;

  sum_89 <= sum_88 + product_127;

  sum_90 <= sum_89 + product_126;

  sum_91 <= sum_90 + product_125;

  sum_92 <= sum_91 + product_124;

  sum_93 <= sum_92 + product_123;

  sum_94 <= sum_93 + product_122;

  sum_95 <= sum_94 + product_121;

  sum_96 <= sum_95 + product_120;

  sum_97 <= sum_96 + product_119;

  sum_98 <= sum_97 + product_118;

  sum_99 <= sum_98 + product_117;

  sum_100 <= sum_99 + product_116;

  sum_101 <= sum_100 + product_115;

  sum_102 <= sum_101 + product_114;

  sum_103 <= sum_102 + product_113;

  sum_104 <= sum_103 + product_112;

  sum_105 <= sum_104 + product_111;

  sum_106 <= sum_105 + product_110;

  sum_107 <= sum_106 + product_109;

  sum_108 <= sum_107 + product_108;

  sum_109 <= sum_108 + product_107;

  sum_110 <= sum_109 + product_106;

  sum_111 <= sum_110 + product_105;

  sum_112 <= sum_111 + product_104;

  sum_113 <= sum_112 + product_103;

  sum_114 <= sum_113 + product_102;

  sum_115 <= sum_114 + product_101;

  sum_116 <= sum_115 + product_100;

  sum_117 <= sum_116 + product_99;

  sum_118 <= sum_117 + product_98;

  sum_119 <= sum_118 + product_97;

  sum_120 <= sum_119 + product_96;

  sum_121 <= sum_120 + product_95;

  sum_122 <= sum_121 + product_94;

  sum_123 <= sum_122 + product_93;

  sum_124 <= sum_123 + product_92;

  sum_125 <= sum_124 + product_91;

  sum_126 <= sum_125 + product_90;

  sum_127 <= sum_126 + product_89;

  sum_128 <= sum_127 + product_88;

  sum_129 <= sum_128 + product_87;

  sum_130 <= sum_129 + product_86;

  sum_131 <= sum_130 + product_85;

  sum_132 <= sum_131 + product_84;

  sum_133 <= sum_132 + product_83;

  sum_134 <= sum_133 + product_82;

  sum_135 <= sum_134 + product_81;

  sum_136 <= sum_135 + product_80;

  sum_137 <= sum_136 + product_79;

  sum_138 <= sum_137 + product_78;

  sum_139 <= sum_138 + product_77;

  sum_140 <= sum_139 + product_76;

  sum_141 <= sum_140 + product_75;

  sum_142 <= sum_141 + product_74;

  sum_143 <= sum_142 + product_73;

  sum_144 <= sum_143 + product_72;

  sum_145 <= sum_144 + product_71;

  sum_146 <= sum_145 + product_70;

  sum_147 <= sum_146 + product_69;

  sum_148 <= sum_147 + product_68;

  sum_149 <= sum_148 + product_67;

  sum_150 <= sum_149 + product_66;

  sum_151 <= sum_150 + product_65;

  sum_152 <= sum_151 + product_64;

  sum_153 <= sum_152 + product_63;

  sum_154 <= sum_153 + product_62;

  sum_155 <= sum_154 + product_61;

  sum_156 <= sum_155 + product_60;

  sum_157 <= sum_156 + product_59;

  sum_158 <= sum_157 + product_58;

  sum_159 <= sum_158 + product_57;

  sum_160 <= sum_159 + product_56;

  sum_161 <= sum_160 + product_55;

  sum_162 <= sum_161 + product_54;

  sum_163 <= sum_162 + product_53;

  sum_164 <= sum_163 + product_52;

  sum_165 <= sum_164 + product_51;

  sum_166 <= sum_165 + product_50;

  sum_167 <= sum_166 + product_49;

  sum_168 <= sum_167 + product_48;

  sum_169 <= sum_168 + product_47;

  sum_170 <= sum_169 + product_46;

  sum_171 <= sum_170 + product_45;

  sum_172 <= sum_171 + product_44;

  sum_173 <= sum_172 + product_43;

  sum_174 <= sum_173 + product_42;

  sum_175 <= sum_174 + product_41;

  sum_176 <= sum_175 + product_40;

  sum_177 <= sum_176 + product_39;

  sum_178 <= sum_177 + product_38;

  sum_179 <= sum_178 + product_37;

  sum_180 <= sum_179 + product_36;

  sum_181 <= sum_180 + product_35;

  sum_182 <= sum_181 + product_34;

  sum_183 <= sum_182 + product_33;

  sum_184 <= sum_183 + product_32;

  sum_185 <= sum_184 + product_31;

  sum_186 <= sum_185 + product_30;

  sum_187 <= sum_186 + product_29;

  sum_188 <= sum_187 + product_28;

  sum_189 <= sum_188 + product_27;

  sum_190 <= sum_189 + product_26;

  sum_191 <= sum_190 + product_25;

  sum_192 <= sum_191 + product_24;

  sum_193 <= sum_192 + product_23;

  sum_194 <= sum_193 + product_22;

  sum_195 <= sum_194 + product_21;

  sum_196 <= sum_195 + product_20;

  sum_197 <= sum_196 + product_19;

  sum_198 <= sum_197 + product_18;

  sum_199 <= sum_198 + product_17;

  sum_200 <= sum_199 + product_16;

  sum_201 <= sum_200 + product_15;

  sum_202 <= sum_201 + product_14;

  sum_203 <= sum_202 + product_13;

  sum_204 <= sum_203 + product_12;

  sum_205 <= sum_204 + product_11;

  sum_206 <= sum_205 + product_10;

  sum_207 <= sum_206 + product_9;

  sum_208 <= sum_207 + product_8;

  sum_209 <= sum_208 + product_7;

  sum_210 <= sum_209 + product_6;

  sum_211 <= sum_210 + product_5;

  sum_212 <= sum_211 + product_4;

  sum_213 <= sum_212 + product_3;

  sum_214 <= sum_213 + product_2;

  sum_215 <= sum_214 + product_1;

  fir_sum <= sum_215 + product;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        output_register <= fir_sum;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  ce_out <= ce_out_phase;
  ce_in <= ce_in_reg;
  filter_out <= output_register;
END rtl;
