-- -------------------------------------------------------------
--
-- Module: IIR_High_Performance
-- Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
-- Generated on: 2023-03-19 15:18:13
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- OptimizeForHDL: on
-- TargetDirectory: C:\Users\John\Desktop\Honours_Project\helper
-- EDAScriptGeneration: off
-- AddPipelineRegisters: on
-- Name: IIR_High_Performance
-- TestBenchStimulus: step ramp chirp 
-- GenerateHDLTestBench: off

-- Filter Specifications:
--
-- Sample Rate     : N/A (normalized frequency)
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Stopband Atten. : 80 dB
-- Passband Ripple : 1 dB
-- Passband Edge   : 0.08
-- Stopband Edge   : 0.16
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 7
-- Stable              : Yes
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s16,13 -> [-4 4)
-- Denominator         : s16,14 -> [-2 2)
-- Scale Values        : s16,20 -> [-3.125000e-02 3.125000e-02)
-- Input               : s28,27 -> [-1 1)
-- Section Input       : s28,26 -> [-2 2)
-- Section Output      : s32,26 -> [-32 32)
-- Output              : s32,26 -> [-32 32)
-- State               : s16,15 -> [-1 1)
-- Numerator Prod      : s32,28 -> [-8 8)
-- Denominator Prod    : s32,29 -> [-4 4)
-- Numerator Accum     : s34,28 -> [-32 32)
-- Denominator Accum   : s34,29 -> [-16 16)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY IIR_High_Performance IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(27 DOWNTO 0); -- sfix28_En27
         filter_out                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En26
         );

END IIR_High_Performance;


----------------------------------------------------------------
--Module Architecture: IIR_High_Performance
----------------------------------------------------------------
ARCHITECTURE rtl OF IIR_High_Performance IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT scaleconst1                    : signed(15 DOWNTO 0) := to_signed(17704, 16); -- sfix16_En20
  CONSTANT coeff_b1_section1              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section1              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section1              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section1              : signed(15 DOWNTO 0) := to_signed(-30730, 16); -- sfix16_En14
  CONSTANT coeff_a3_section1              : signed(15 DOWNTO 0) := to_signed(15452, 16); -- sfix16_En14
  CONSTANT scaleconst2                    : signed(15 DOWNTO 0) := to_signed(16774, 16); -- sfix16_En20
  CONSTANT coeff_b1_section2              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section2              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section2              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section2              : signed(15 DOWNTO 0) := to_signed(-29116, 16); -- sfix16_En14
  CONSTANT coeff_a3_section2              : signed(15 DOWNTO 0) := to_signed(13780, 16); -- sfix16_En14
  CONSTANT scaleconst3                    : signed(15 DOWNTO 0) := to_signed(15998, 16); -- sfix16_En20
  CONSTANT coeff_b1_section3              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section3              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section3              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section3              : signed(15 DOWNTO 0) := to_signed(-27768, 16); -- sfix16_En14
  CONSTANT coeff_a3_section3              : signed(15 DOWNTO 0) := to_signed(12384, 16); -- sfix16_En14
  CONSTANT scaleconst4                    : signed(15 DOWNTO 0) := to_signed(15380, 16); -- sfix16_En20
  CONSTANT coeff_b1_section4              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section4              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section4              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section4              : signed(15 DOWNTO 0) := to_signed(-26696, 16); -- sfix16_En14
  CONSTANT coeff_a3_section4              : signed(15 DOWNTO 0) := to_signed(11273, 16); -- sfix16_En14
  CONSTANT scaleconst5                    : signed(15 DOWNTO 0) := to_signed(14920, 16); -- sfix16_En20
  CONSTANT coeff_b1_section5              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section5              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section5              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section5              : signed(15 DOWNTO 0) := to_signed(-25898, 16); -- sfix16_En14
  CONSTANT coeff_a3_section5              : signed(15 DOWNTO 0) := to_signed(10447, 16); -- sfix16_En14
  CONSTANT scaleconst6                    : signed(15 DOWNTO 0) := to_signed(14617, 16); -- sfix16_En20
  CONSTANT coeff_b1_section6              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section6              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section6              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section6              : signed(15 DOWNTO 0) := to_signed(-25371, 16); -- sfix16_En14
  CONSTANT coeff_a3_section6              : signed(15 DOWNTO 0) := to_signed(9900, 16); -- sfix16_En14
  CONSTANT scaleconst7                    : signed(15 DOWNTO 0) := to_signed(14465, 16); -- sfix16_En20
  CONSTANT coeff_b1_section7              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_b2_section7              : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En13
  CONSTANT coeff_b3_section7              : signed(15 DOWNTO 0) := to_signed(8192, 16); -- sfix16_En13
  CONSTANT coeff_a2_section7              : signed(15 DOWNTO 0) := to_signed(-25108, 16); -- sfix16_En14
  CONSTANT coeff_a3_section7              : signed(15 DOWNTO 0) := to_signed(9628, 16); -- sfix16_En14
  -- Signals
  SIGNAL input_register                   : signed(27 DOWNTO 0); -- sfix28_En27
  SIGNAL scale1                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp                         : signed(43 DOWNTO 0); -- sfix44_En47
  SIGNAL scaletypeconvert1                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum1                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum1                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum1                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert1                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv1                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul1                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul1                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul1                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast                         : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_1                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp                         : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_2                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_3                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_1                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert1                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast                         : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_1                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp                         : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_2                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_3                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_1                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL section_result1                  : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL sos_pipeline1                    : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL scale2                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp_1                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL scaletypeconvert2                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 2 Signals 
  SIGNAL a1sum2                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum2                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum2                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum2                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert2                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv2                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul2                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul2                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul2                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast_4                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_5                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_2                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_6                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_7                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_3                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert2                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_4                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_5                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_2                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_6                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_7                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_3                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL section_result2                  : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL sos_pipeline2                    : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL scale3                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp_2                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL scaletypeconvert3                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 3 Signals 
  SIGNAL a1sum3                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum3                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum3                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum3                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert3                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv3                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul3                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul3                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul3                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast_8                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_9                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_4                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_10                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_11                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_5                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert3                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_8                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_9                       : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_4                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_10                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_11                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_5                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL section_result3                  : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL sos_pipeline3                    : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL scale4                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp_3                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL scaletypeconvert4                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 4 Signals 
  SIGNAL a1sum4                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum4                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum4                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum4                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert4                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv4                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul4                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul4                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul4                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast_12                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_13                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_6                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_14                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_15                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_7                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert4                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_12                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_13                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_6                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_14                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_15                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_7                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL section_result4                  : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL sos_pipeline4                    : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL scale5                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp_4                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL scaletypeconvert5                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 5 Signals 
  SIGNAL a1sum5                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum5                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum5                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum5                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert5                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section5                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv5                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul5                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul5                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul5                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast_16                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_17                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_8                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_18                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_19                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_9                       : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert5                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_16                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_17                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_8                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_18                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_19                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_9                       : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL section_result5                  : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL sos_pipeline5                    : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL scale6                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp_5                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL scaletypeconvert6                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 6 Signals 
  SIGNAL a1sum6                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum6                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum6                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum6                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert6                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section6                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv6                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul6                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul6                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul6                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast_20                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_21                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_10                      : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_22                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_23                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_11                      : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert6                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_20                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_21                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_10                      : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_22                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_23                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_11                      : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL section_result6                  : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL sos_pipeline6                    : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL scale7                           : signed(48 DOWNTO 0); -- sfix49_En47
  SIGNAL mul_temp_6                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL scaletypeconvert7                : signed(27 DOWNTO 0); -- sfix28_En26
  -- Section 7 Signals 
  SIGNAL a1sum7                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2sum7                           : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL b1sum7                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL b2sum7                           : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL typeconvert7                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section7                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv7                       : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL a2mul7                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL a3mul7                           : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL b2mul7                           : signed(31 DOWNTO 0); -- sfix32_En28
  SIGNAL sub_cast_24                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_25                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_12                      : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL sub_cast_26                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_cast_27                      : signed(33 DOWNTO 0); -- sfix34_En29
  SIGNAL sub_temp_13                      : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL b1multypeconvert7                : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_24                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_25                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_12                      : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL add_cast_26                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_cast_27                      : signed(33 DOWNTO 0); -- sfix34_En28
  SIGNAL add_temp_13                      : signed(34 DOWNTO 0); -- sfix35_En28
  SIGNAL output_typeconvert               : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL output_register                  : signed(31 DOWNTO 0); -- sfix32_En26


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  mul_temp <= input_register * scaleconst1;
  scale1 <= resize(mul_temp, 49);

  scaletypeconvert1 <= resize(shift_right(scale1(48 DOWNTO 0) + ( "0" & (scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21) & NOT scale1(21))), 21), 28);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(29 DOWNTO 0) + ( "0" & (a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14) & NOT a1sum1(14))), 14), 16);

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= resize(scaletypeconvert1(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b2mul1 <= resize(delay_section1(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast <= inputconv1;
  sub_cast_1 <= resize(a2mul1, 34);
  sub_temp <= resize(sub_cast, 35) - resize(sub_cast_1, 35);
  a2sum1 <= sub_temp(33 DOWNTO 0);

  sub_cast_2 <= a2sum1;
  sub_cast_3 <= resize(a3mul1, 34);
  sub_temp_1 <= resize(sub_cast_2, 35) - resize(sub_cast_3, 35);
  a1sum1 <= sub_temp_1(33 DOWNTO 0);

  b1multypeconvert1 <= resize(typeconvert1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(b2mul1, 34);
  add_temp <= resize(add_cast, 35) + resize(add_cast_1, 35);
  b2sum1 <= add_temp(33 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(delay_section1(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_1 <= resize(add_cast_2, 35) + resize(add_cast_3, 35);
  b1sum1 <= add_temp_1(33 DOWNTO 0);

  section_result1 <= resize(shift_right(b1sum1(33 DOWNTO 0) + ( "0" & (b1sum1(2) & NOT b1sum1(2))), 2), 32);

  sos_pipeline_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sos_pipeline1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sos_pipeline1 <= section_result1;
      END IF;
    END IF; 
  END PROCESS sos_pipeline_process_section1;

  mul_temp_1 <= sos_pipeline1 * scaleconst2;
  scale2 <= resize(mul_temp_1(47 DOWNTO 0) & '0', 49);

  scaletypeconvert2 <= resize(shift_right(scale2(48 DOWNTO 0) + ( "0" & (scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21) & NOT scale2(21))), 21), 28);

  --   ------------------ Section 2 ------------------

  typeconvert2 <= resize(shift_right(a1sum2(29 DOWNTO 0) + ( "0" & (a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14) & NOT a1sum2(14))), 14), 16);

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= typeconvert2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= resize(scaletypeconvert2(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b2mul2 <= resize(delay_section2(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast_4 <= inputconv2;
  sub_cast_5 <= resize(a2mul2, 34);
  sub_temp_2 <= resize(sub_cast_4, 35) - resize(sub_cast_5, 35);
  a2sum2 <= sub_temp_2(33 DOWNTO 0);

  sub_cast_6 <= a2sum2;
  sub_cast_7 <= resize(a3mul2, 34);
  sub_temp_3 <= resize(sub_cast_6, 35) - resize(sub_cast_7, 35);
  a1sum2 <= sub_temp_3(33 DOWNTO 0);

  b1multypeconvert2 <= resize(typeconvert2(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast_4 <= b1multypeconvert2;
  add_cast_5 <= resize(b2mul2, 34);
  add_temp_2 <= resize(add_cast_4, 35) + resize(add_cast_5, 35);
  b2sum2 <= add_temp_2(33 DOWNTO 0);

  add_cast_6 <= b2sum2;
  add_cast_7 <= resize(delay_section2(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_3 <= resize(add_cast_6, 35) + resize(add_cast_7, 35);
  b1sum2 <= add_temp_3(33 DOWNTO 0);

  section_result2 <= resize(shift_right(b1sum2(33 DOWNTO 0) + ( "0" & (b1sum2(2) & NOT b1sum2(2))), 2), 32);

  sos_pipeline_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sos_pipeline2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sos_pipeline2 <= section_result2;
      END IF;
    END IF; 
  END PROCESS sos_pipeline_process_section2;

  mul_temp_2 <= sos_pipeline2 * scaleconst3;
  scale3 <= resize(mul_temp_2(47 DOWNTO 0) & '0', 49);

  scaletypeconvert3 <= resize(shift_right(scale3(48 DOWNTO 0) + ( "0" & (scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21) & NOT scale3(21))), 21), 28);

  --   ------------------ Section 3 ------------------

  typeconvert3 <= resize(shift_right(a1sum3(29 DOWNTO 0) + ( "0" & (a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14) & NOT a1sum3(14))), 14), 16);

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= typeconvert3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= resize(scaletypeconvert3(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b2mul3 <= resize(delay_section3(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast_8 <= inputconv3;
  sub_cast_9 <= resize(a2mul3, 34);
  sub_temp_4 <= resize(sub_cast_8, 35) - resize(sub_cast_9, 35);
  a2sum3 <= sub_temp_4(33 DOWNTO 0);

  sub_cast_10 <= a2sum3;
  sub_cast_11 <= resize(a3mul3, 34);
  sub_temp_5 <= resize(sub_cast_10, 35) - resize(sub_cast_11, 35);
  a1sum3 <= sub_temp_5(33 DOWNTO 0);

  b1multypeconvert3 <= resize(typeconvert3(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast_8 <= b1multypeconvert3;
  add_cast_9 <= resize(b2mul3, 34);
  add_temp_4 <= resize(add_cast_8, 35) + resize(add_cast_9, 35);
  b2sum3 <= add_temp_4(33 DOWNTO 0);

  add_cast_10 <= b2sum3;
  add_cast_11 <= resize(delay_section3(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_5 <= resize(add_cast_10, 35) + resize(add_cast_11, 35);
  b1sum3 <= add_temp_5(33 DOWNTO 0);

  section_result3 <= resize(shift_right(b1sum3(33 DOWNTO 0) + ( "0" & (b1sum3(2) & NOT b1sum3(2))), 2), 32);

  sos_pipeline_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sos_pipeline3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sos_pipeline3 <= section_result3;
      END IF;
    END IF; 
  END PROCESS sos_pipeline_process_section3;

  mul_temp_3 <= sos_pipeline3 * scaleconst4;
  scale4 <= resize(mul_temp_3(47 DOWNTO 0) & '0', 49);

  scaletypeconvert4 <= resize(shift_right(scale4(48 DOWNTO 0) + ( "0" & (scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21) & NOT scale4(21))), 21), 28);

  --   ------------------ Section 4 ------------------

  typeconvert4 <= resize(shift_right(a1sum4(29 DOWNTO 0) + ( "0" & (a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14) & NOT a1sum4(14))), 14), 16);

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= typeconvert4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= resize(scaletypeconvert4(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b2mul4 <= resize(delay_section4(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast_12 <= inputconv4;
  sub_cast_13 <= resize(a2mul4, 34);
  sub_temp_6 <= resize(sub_cast_12, 35) - resize(sub_cast_13, 35);
  a2sum4 <= sub_temp_6(33 DOWNTO 0);

  sub_cast_14 <= a2sum4;
  sub_cast_15 <= resize(a3mul4, 34);
  sub_temp_7 <= resize(sub_cast_14, 35) - resize(sub_cast_15, 35);
  a1sum4 <= sub_temp_7(33 DOWNTO 0);

  b1multypeconvert4 <= resize(typeconvert4(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast_12 <= b1multypeconvert4;
  add_cast_13 <= resize(b2mul4, 34);
  add_temp_6 <= resize(add_cast_12, 35) + resize(add_cast_13, 35);
  b2sum4 <= add_temp_6(33 DOWNTO 0);

  add_cast_14 <= b2sum4;
  add_cast_15 <= resize(delay_section4(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_7 <= resize(add_cast_14, 35) + resize(add_cast_15, 35);
  b1sum4 <= add_temp_7(33 DOWNTO 0);

  section_result4 <= resize(shift_right(b1sum4(33 DOWNTO 0) + ( "0" & (b1sum4(2) & NOT b1sum4(2))), 2), 32);

  sos_pipeline_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sos_pipeline4 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sos_pipeline4 <= section_result4;
      END IF;
    END IF; 
  END PROCESS sos_pipeline_process_section4;

  mul_temp_4 <= sos_pipeline4 * scaleconst5;
  scale5 <= resize(mul_temp_4(47 DOWNTO 0) & '0', 49);

  scaletypeconvert5 <= resize(shift_right(scale5(48 DOWNTO 0) + ( "0" & (scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21) & NOT scale5(21))), 21), 28);

  --   ------------------ Section 5 ------------------

  typeconvert5 <= resize(shift_right(a1sum5(29 DOWNTO 0) + ( "0" & (a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14) & NOT a1sum5(14))), 14), 16);

  delay_process_section5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section5 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section5(1) <= delay_section5(0);
        delay_section5(0) <= typeconvert5;
      END IF;
    END IF;
  END PROCESS delay_process_section5;

  inputconv5 <= resize(scaletypeconvert5(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul5 <= delay_section5(0) * coeff_a2_section5;

  a3mul5 <= delay_section5(1) * coeff_a3_section5;

  b2mul5 <= resize(delay_section5(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast_16 <= inputconv5;
  sub_cast_17 <= resize(a2mul5, 34);
  sub_temp_8 <= resize(sub_cast_16, 35) - resize(sub_cast_17, 35);
  a2sum5 <= sub_temp_8(33 DOWNTO 0);

  sub_cast_18 <= a2sum5;
  sub_cast_19 <= resize(a3mul5, 34);
  sub_temp_9 <= resize(sub_cast_18, 35) - resize(sub_cast_19, 35);
  a1sum5 <= sub_temp_9(33 DOWNTO 0);

  b1multypeconvert5 <= resize(typeconvert5(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast_16 <= b1multypeconvert5;
  add_cast_17 <= resize(b2mul5, 34);
  add_temp_8 <= resize(add_cast_16, 35) + resize(add_cast_17, 35);
  b2sum5 <= add_temp_8(33 DOWNTO 0);

  add_cast_18 <= b2sum5;
  add_cast_19 <= resize(delay_section5(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_9 <= resize(add_cast_18, 35) + resize(add_cast_19, 35);
  b1sum5 <= add_temp_9(33 DOWNTO 0);

  section_result5 <= resize(shift_right(b1sum5(33 DOWNTO 0) + ( "0" & (b1sum5(2) & NOT b1sum5(2))), 2), 32);

  sos_pipeline_process_section5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sos_pipeline5 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sos_pipeline5 <= section_result5;
      END IF;
    END IF; 
  END PROCESS sos_pipeline_process_section5;

  mul_temp_5 <= sos_pipeline5 * scaleconst6;
  scale6 <= resize(mul_temp_5(47 DOWNTO 0) & '0', 49);

  scaletypeconvert6 <= resize(shift_right(scale6(48 DOWNTO 0) + ( "0" & (scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21) & NOT scale6(21))), 21), 28);

  --   ------------------ Section 6 ------------------

  typeconvert6 <= resize(shift_right(a1sum6(29 DOWNTO 0) + ( "0" & (a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14) & NOT a1sum6(14))), 14), 16);

  delay_process_section6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section6 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section6(1) <= delay_section6(0);
        delay_section6(0) <= typeconvert6;
      END IF;
    END IF;
  END PROCESS delay_process_section6;

  inputconv6 <= resize(scaletypeconvert6(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul6 <= delay_section6(0) * coeff_a2_section6;

  a3mul6 <= delay_section6(1) * coeff_a3_section6;

  b2mul6 <= resize(delay_section6(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast_20 <= inputconv6;
  sub_cast_21 <= resize(a2mul6, 34);
  sub_temp_10 <= resize(sub_cast_20, 35) - resize(sub_cast_21, 35);
  a2sum6 <= sub_temp_10(33 DOWNTO 0);

  sub_cast_22 <= a2sum6;
  sub_cast_23 <= resize(a3mul6, 34);
  sub_temp_11 <= resize(sub_cast_22, 35) - resize(sub_cast_23, 35);
  a1sum6 <= sub_temp_11(33 DOWNTO 0);

  b1multypeconvert6 <= resize(typeconvert6(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast_20 <= b1multypeconvert6;
  add_cast_21 <= resize(b2mul6, 34);
  add_temp_10 <= resize(add_cast_20, 35) + resize(add_cast_21, 35);
  b2sum6 <= add_temp_10(33 DOWNTO 0);

  add_cast_22 <= b2sum6;
  add_cast_23 <= resize(delay_section6(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_11 <= resize(add_cast_22, 35) + resize(add_cast_23, 35);
  b1sum6 <= add_temp_11(33 DOWNTO 0);

  section_result6 <= resize(shift_right(b1sum6(33 DOWNTO 0) + ( "0" & (b1sum6(2) & NOT b1sum6(2))), 2), 32);

  sos_pipeline_process_section6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sos_pipeline6 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sos_pipeline6 <= section_result6;
      END IF;
    END IF; 
  END PROCESS sos_pipeline_process_section6;

  mul_temp_6 <= sos_pipeline6 * scaleconst7;
  scale7 <= resize(mul_temp_6(47 DOWNTO 0) & '0', 49);

  scaletypeconvert7 <= resize(shift_right(scale7(48 DOWNTO 0) + ( "0" & (scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21) & NOT scale7(21))), 21), 28);

  --   ------------------ Section 7 ------------------

  typeconvert7 <= resize(shift_right(a1sum7(29 DOWNTO 0) + ( "0" & (a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14) & NOT a1sum7(14))), 14), 16);

  delay_process_section7 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section7 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section7(1) <= delay_section7(0);
        delay_section7(0) <= typeconvert7;
      END IF;
    END IF;
  END PROCESS delay_process_section7;

  inputconv7 <= resize(scaletypeconvert7(27 DOWNTO 0) & '0' & '0' & '0', 34);

  a2mul7 <= delay_section7(0) * coeff_a2_section7;

  a3mul7 <= delay_section7(1) * coeff_a3_section7;

  b2mul7 <= resize(delay_section7(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sub_cast_24 <= inputconv7;
  sub_cast_25 <= resize(a2mul7, 34);
  sub_temp_12 <= resize(sub_cast_24, 35) - resize(sub_cast_25, 35);
  a2sum7 <= sub_temp_12(33 DOWNTO 0);

  sub_cast_26 <= a2sum7;
  sub_cast_27 <= resize(a3mul7, 34);
  sub_temp_13 <= resize(sub_cast_26, 35) - resize(sub_cast_27, 35);
  a1sum7 <= sub_temp_13(33 DOWNTO 0);

  b1multypeconvert7 <= resize(typeconvert7(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);

  add_cast_24 <= b1multypeconvert7;
  add_cast_25 <= resize(b2mul7, 34);
  add_temp_12 <= resize(add_cast_24, 35) + resize(add_cast_25, 35);
  b2sum7 <= add_temp_12(33 DOWNTO 0);

  add_cast_26 <= b2sum7;
  add_cast_27 <= resize(delay_section7(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  add_temp_13 <= resize(add_cast_26, 35) + resize(add_cast_27, 35);
  b1sum7 <= add_temp_13(33 DOWNTO 0);

  output_typeconvert <= resize(shift_right(b1sum7(33 DOWNTO 0) + ( "0" & (b1sum7(2) & NOT b1sum7(2))), 2), 32);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
