-- -------------------------------------------------------------
--
-- Module: LiteHPFilter
-- Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
-- Generated on: 2023-09-11 17:44:19
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- OptimizeForHDL: on
-- AddPipelineRegisters: on
-- Name: LiteHPFilter
-- TestBenchName: Hhp_tb
-- TestBenchStimulus: impulse step ramp chirp noise 

-- Filter Specifications:
--
-- Sample Rate     : 125 MHz
-- Response        : Highpass
-- Specification   : N,Fp,Ast,Ap
-- Stopband Atten. : 60 dB
-- Passband Ripple : 1 dB
-- Filter Order    : 32
-- Passband Edge   : 3 MHz
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 33
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,15 -> [-1 1)
-- Input             : s14,0 -> [-8192 8192)
-- Filter Internals  : Full Precision
--   Output          : s30,15 -> [-16384 16384)  (auto determined)
--   Product         : s29,15 -> [-8192 8192)  (auto determined)
--   Accumulator     : s30,15 -> [-16384 16384)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY LiteHPFilter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(13 DOWNTO 0); -- sfix14
         filter_out                      :   OUT   std_logic_vector(29 DOWNTO 0)  -- sfix30_En15
         );

END LiteHPFilter;


----------------------------------------------------------------
--Module Architecture: LiteHPFilter
----------------------------------------------------------------
ARCHITECTURE rtl OF LiteHPFilter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(13 DOWNTO 0); -- sfix14
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-1032, 16); -- sfix16_En15
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-187, 16); -- sfix16_En15
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(-203, 16); -- sfix16_En15
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(-218, 16); -- sfix16_En15
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(-233, 16); -- sfix16_En15
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(-247, 16); -- sfix16_En15
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(-260, 16); -- sfix16_En15
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(-273, 16); -- sfix16_En15
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(-284, 16); -- sfix16_En15
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(-295, 16); -- sfix16_En15
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(-304, 16); -- sfix16_En15
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(-312, 16); -- sfix16_En15
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(-319, 16); -- sfix16_En15
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(-324, 16); -- sfix16_En15
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(-328, 16); -- sfix16_En15
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(-330, 16); -- sfix16_En15
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(32437, 16); -- sfix16_En15
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(-330, 16); -- sfix16_En15
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(-328, 16); -- sfix16_En15
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(-324, 16); -- sfix16_En15
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(-319, 16); -- sfix16_En15
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(-312, 16); -- sfix16_En15
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(-304, 16); -- sfix16_En15
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(-295, 16); -- sfix16_En15
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(-284, 16); -- sfix16_En15
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(-273, 16); -- sfix16_En15
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(-260, 16); -- sfix16_En15
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(-247, 16); -- sfix16_En15
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(-233, 16); -- sfix16_En15
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(-218, 16); -- sfix16_En15
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(-203, 16); -- sfix16_En15
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(-187, 16); -- sfix16_En15
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(-1032, 16); -- sfix16_En15

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 32); -- sfix14
  SIGNAL product33                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp                         : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product32                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product31                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product30                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_3                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product29                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_4                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product28                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_5                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product27                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_6                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product26                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_7                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product25                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_8                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product24                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_9                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product23                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_10                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product22                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_11                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product21                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_12                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product20                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_13                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product19                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_14                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product18                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_15                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product17                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_16                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product16                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_17                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product15                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_18                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product14                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_19                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product13                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_20                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product12                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_21                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product11                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_22                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product10                        : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_23                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product9                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_24                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product8                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_25                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product7                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_26                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product6                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_27                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product5                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_28                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product4                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_29                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product3                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_30                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product2                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_31                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL product1                         : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL mul_temp_32                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum_final                        : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_1                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_2                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_3                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_3                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_4                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_4                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_5                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_5                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_6                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_6                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_7                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_7                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_8                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_8                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_9                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_9                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_10                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_10                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_11                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_11                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_12                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_12                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_13                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_13                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_14                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_14                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_15                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_15                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1_16                          : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_16                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe1_17                      : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL sum2_1                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp                         : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_2                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_1                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_3                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_2                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_3                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_4                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_3                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_4                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_5                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_4                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_5                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_6                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_5                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_6                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_7                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_6                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_7                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2_8                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_7                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe2_8                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe2_9                       : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL sum3_1                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_8                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe3_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum3_2                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_9                       : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe3_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum3_3                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_10                      : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe3_3                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum3_4                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_11                      : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe3_4                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe3_5                       : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL sum4_1                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_12                      : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe4_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum4_2                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_13                      : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe4_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe4_3                       : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL sum5_1                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_14                      : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe5_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sumpipe5_2                       : signed(28 DOWNTO 0); -- sfix29_En15
  SIGNAL sum6_1                           : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_15                      : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL sumpipe6_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL output_typeconvert               : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL output_register                  : signed(29 DOWNTO 0); -- sfix30_En15


BEGIN

  process(clk)
  begin
    if rising_edge(clk) then
      if reset = '1' then

        delay_pipeline(0 TO 32) <= (others => (others => '0'));
         product33                        <= (others => '0'); -- sfix29_En15
         mul_temp                         <= (others => '0'); -- sfix30_En15
         product32                        <= (others => '0'); -- sfix29_En15
         mul_temp_1                       <= (others => '0'); -- sfix30_En15
         product31                        <= (others => '0'); -- sfix29_En15
         mul_temp_2                       <= (others => '0'); -- sfix30_En15
         product30                        <= (others => '0'); -- sfix29_En15
         mul_temp_3                       <= (others => '0'); -- sfix30_En15
         product29                        <= (others => '0'); -- sfix29_En15
         mul_temp_4                       <= (others => '0'); -- sfix30_En15
         product28                        <= (others => '0'); -- sfix29_En15
         mul_temp_5                       <= (others => '0'); -- sfix30_En15
         product27                        <= (others => '0'); -- sfix29_En15
         mul_temp_6                       <= (others => '0'); -- sfix30_En15
         product26                        <= (others => '0'); -- sfix29_En15
         mul_temp_7                       <= (others => '0'); -- sfix30_En15
         product25                        <= (others => '0'); -- sfix29_En15
         mul_temp_8                       <= (others => '0'); -- sfix30_En15
         product24                        <= (others => '0'); -- sfix29_En15
         mul_temp_9                       <= (others => '0'); -- sfix30_En15
         product23                        <= (others => '0'); -- sfix29_En15
         mul_temp_10                      <= (others => '0'); -- sfix30_En15
         product22                        <= (others => '0'); -- sfix29_En15
         mul_temp_11                      <= (others => '0'); -- sfix30_En15
         product21                        <= (others => '0'); -- sfix29_En15
         mul_temp_12                      <= (others => '0'); -- sfix30_En15
         product20                        <= (others => '0'); -- sfix29_En15
         mul_temp_13                      <= (others => '0'); -- sfix30_En15
         product19                        <= (others => '0'); -- sfix29_En15
         mul_temp_14                      <= (others => '0'); -- sfix30_En15
         product18                        <= (others => '0'); -- sfix29_En15
         mul_temp_15                      <= (others => '0'); -- sfix30_En15
         product17                        <= (others => '0'); -- sfix29_En15
         mul_temp_16                      <= (others => '0'); -- sfix30_En15
         product16                        <= (others => '0'); -- sfix29_En15
         mul_temp_17                      <= (others => '0'); -- sfix30_En15
         product15                        <= (others => '0'); -- sfix29_En15
         mul_temp_18                      <= (others => '0'); -- sfix30_En15
         product14                        <= (others => '0'); -- sfix29_En15
         mul_temp_19                      <= (others => '0'); -- sfix30_En15
         product13                        <= (others => '0'); -- sfix29_En15
         mul_temp_20                      <= (others => '0'); -- sfix30_En15
         product12                        <= (others => '0'); -- sfix29_En15
         mul_temp_21                      <= (others => '0'); -- sfix30_En15
         product11                        <= (others => '0'); -- sfix29_En15
         mul_temp_22                      <= (others => '0'); -- sfix30_En15
         product10                        <= (others => '0'); -- sfix29_En15
         mul_temp_23                      <= (others => '0'); -- sfix30_En15
         product9                         <= (others => '0'); -- sfix29_En15
         mul_temp_24                      <= (others => '0'); -- sfix30_En15
         product8                         <= (others => '0'); -- sfix29_En15
         mul_temp_25                      <= (others => '0'); -- sfix30_En15
         product7                         <= (others => '0'); -- sfix29_En15
         mul_temp_26                      <= (others => '0'); -- sfix30_En15
         product6                         <= (others => '0'); -- sfix29_En15
         mul_temp_27                      <= (others => '0'); -- sfix30_En15
         product5                         <= (others => '0'); -- sfix29_En15
         mul_temp_28                      <= (others => '0'); -- sfix30_En15
         product4                         <= (others => '0'); -- sfix29_En15
         mul_temp_29                      <= (others => '0'); -- sfix30_En15
         product3                         <= (others => '0'); -- sfix29_En15
         mul_temp_30                      <= (others => '0'); -- sfix30_En15
         product2                         <= (others => '0'); -- sfix29_En15
         mul_temp_31                      <= (others => '0'); -- sfix30_En15
         product1                         <= (others => '0'); -- sfix29_En15
         mul_temp_32                      <= (others => '0'); -- sfix30_En15
         sum_final                        <= (others => '0'); -- sfix30_En15
         sum1_1                           <= (others => '0'); -- sfix30_En15
         sumpipe1_1                       <= (others => '0'); -- sfix30_En15
         sum1_2                           <= (others => '0'); -- sfix30_En15
         sumpipe1_2                       <= (others => '0'); -- sfix30_En15
         sum1_3                           <= (others => '0'); -- sfix30_En15
         sumpipe1_3                       <= (others => '0'); -- sfix30_En15
         sum1_4                           <= (others => '0'); -- sfix30_En15
         sumpipe1_4                       <= (others => '0'); -- sfix30_En15
         sum1_5                           <= (others => '0'); -- sfix30_En15
         sumpipe1_5                       <= (others => '0'); -- sfix30_En15
         sum1_6                           <= (others => '0'); -- sfix30_En15
         sumpipe1_6                       <= (others => '0'); -- sfix30_En15
         sum1_7                           <= (others => '0'); -- sfix30_En15
         sumpipe1_7                       <= (others => '0'); -- sfix30_En15
         sum1_8                           <= (others => '0'); -- sfix30_En15
         sumpipe1_8                       <= (others => '0'); -- sfix30_En15
         sum1_9                           <= (others => '0'); -- sfix30_En15
         sumpipe1_9                       <= (others => '0'); -- sfix30_En15
         sum1_10                          <= (others => '0'); -- sfix30_En15
         sumpipe1_10                      <= (others => '0'); -- sfix30_En15
         sum1_11                          <= (others => '0'); -- sfix30_En15
         sumpipe1_11                      <= (others => '0'); -- sfix30_En15
         sum1_12                          <= (others => '0'); -- sfix30_En15
         sumpipe1_12                      <= (others => '0'); -- sfix30_En15
         sum1_13                          <= (others => '0'); -- sfix30_En15
         sumpipe1_13                      <= (others => '0'); -- sfix30_En15
         sum1_14                          <= (others => '0'); -- sfix30_En15
         sumpipe1_14                      <= (others => '0'); -- sfix30_En15
         sum1_15                          <= (others => '0'); -- sfix30_En15
         sumpipe1_15                      <= (others => '0'); -- sfix30_En15
         sum1_16                          <= (others => '0'); -- sfix30_En15
         sumpipe1_16                      <= (others => '0'); -- sfix30_En15
         sumpipe1_17                      <= (others => '0'); -- sfix29_En15
         sum2_1                           <= (others => '0'); -- sfix30_En15
         add_temp                         <= (others => '0'); -- sfix31_En15
         sumpipe2_1                       <= (others => '0'); -- sfix30_En15
         sum2_2                           <= (others => '0'); -- sfix30_En15
         add_temp_1                       <= (others => '0'); -- sfix31_En15
         sumpipe2_2                       <= (others => '0'); -- sfix30_En15
         sum2_3                           <= (others => '0'); -- sfix30_En15
         add_temp_2                       <= (others => '0'); -- sfix31_En15
         sumpipe2_3                       <= (others => '0'); -- sfix30_En15
         sum2_4                           <= (others => '0'); -- sfix30_En15
         add_temp_3                       <= (others => '0'); -- sfix31_En15
         sumpipe2_4                       <= (others => '0'); -- sfix30_En15
         sum2_5                           <= (others => '0'); -- sfix30_En15
         add_temp_4                       <= (others => '0'); -- sfix31_En15
         sumpipe2_5                       <= (others => '0'); -- sfix30_En15
         sum2_6                           <= (others => '0'); -- sfix30_En15
         add_temp_5                       <= (others => '0'); -- sfix31_En15
         sumpipe2_6                       <= (others => '0'); -- sfix30_En15
         sum2_7                           <= (others => '0'); -- sfix30_En15
         add_temp_6                       <= (others => '0'); -- sfix31_En15
         sumpipe2_7                       <= (others => '0'); -- sfix30_En15
         sum2_8                           <= (others => '0'); -- sfix30_En15
         add_temp_7                       <= (others => '0'); -- sfix31_En15
         sumpipe2_8                       <= (others => '0'); -- sfix30_En15
         sumpipe2_9                       <= (others => '0'); -- sfix29_En15
         sum3_1                           <= (others => '0'); -- sfix30_En15
         add_temp_8                       <= (others => '0'); -- sfix31_En15
         sumpipe3_1                       <= (others => '0'); -- sfix30_En15
         sum3_2                           <= (others => '0'); -- sfix30_En15
         add_temp_9                       <= (others => '0'); -- sfix31_En15
         sumpipe3_2                       <= (others => '0'); -- sfix30_En15
         sum3_3                           <= (others => '0'); -- sfix30_En15
         add_temp_10                      <= (others => '0'); -- sfix31_En15
         sumpipe3_3                       <= (others => '0'); -- sfix30_En15
         sum3_4                           <= (others => '0'); -- sfix30_En15
         add_temp_11                      <= (others => '0'); -- sfix31_En15
         sumpipe3_4                       <= (others => '0'); -- sfix30_En15
         sumpipe3_5                       <= (others => '0'); -- sfix29_En15
         sum4_1                           <= (others => '0'); -- sfix30_En15
         add_temp_12                      <= (others => '0'); -- sfix31_En15
         sumpipe4_1                       <= (others => '0'); -- sfix30_En15
         sum4_2                           <= (others => '0'); -- sfix30_En15
         add_temp_13                      <= (others => '0'); -- sfix31_En15
         sumpipe4_2                       <= (others => '0'); -- sfix30_En15
         sumpipe4_3                       <= (others => '0'); -- sfix29_En15
         sum5_1                           <= (others => '0'); -- sfix30_En15
         add_temp_14                      <= (others => '0'); -- sfix31_En15
         sumpipe5_1                       <= (others => '0'); -- sfix30_En15
         sumpipe5_2                       <= (others => '0'); -- sfix29_En15
         sum6_1                           <= (others => '0'); -- sfix30_En15
         add_temp_15                      <= (others => '0'); -- sfix31_En15
         sumpipe6_1                       <= (others => '0'); -- sfix30_En15
         output_typeconvert               <= (others => '0'); -- sfix30_En15
         output_register                  <= (others => '0'); -- sfix30_En15



        
      else

        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 32) <= delay_pipeline(0 TO 31);

        mul_temp <= delay_pipeline(32) * coeff33;
        product33 <= mul_temp(28 DOWNTO 0);
        mul_temp_1 <= delay_pipeline(31) * coeff32;
        product32 <= mul_temp_1(28 DOWNTO 0);
        mul_temp_2 <= delay_pipeline(30) * coeff31;
        product31 <= mul_temp_2(28 DOWNTO 0);
        mul_temp_3 <= delay_pipeline(29) * coeff30;
        product30 <= mul_temp_3(28 DOWNTO 0);
        mul_temp_4 <= delay_pipeline(28) * coeff29;
        product29 <= mul_temp_4(28 DOWNTO 0);
        mul_temp_5 <= delay_pipeline(27) * coeff28;
        product28 <= mul_temp_5(28 DOWNTO 0);
        mul_temp_6 <= delay_pipeline(26) * coeff27;
        product27 <= mul_temp_6(28 DOWNTO 0);
        mul_temp_7 <= delay_pipeline(25) * coeff26;
        product26 <= mul_temp_7(28 DOWNTO 0);
        mul_temp_8 <= delay_pipeline(24) * coeff25;
        product25 <= mul_temp_8(28 DOWNTO 0);
        mul_temp_9 <= delay_pipeline(23) * coeff24;
        product24 <= mul_temp_9(28 DOWNTO 0);
        mul_temp_10 <= delay_pipeline(22) * coeff23;
        product23 <= mul_temp_10(28 DOWNTO 0);
        mul_temp_11 <= delay_pipeline(21) * coeff22;
        product22 <= mul_temp_11(28 DOWNTO 0);
        mul_temp_12 <= delay_pipeline(20) * coeff21;
        product21 <= mul_temp_12(28 DOWNTO 0);
        mul_temp_13 <= delay_pipeline(19) * coeff20;
        product20 <= mul_temp_13(28 DOWNTO 0);
        mul_temp_14 <= delay_pipeline(18) * coeff19;
        product19 <= mul_temp_14(28 DOWNTO 0);
        mul_temp_15 <= delay_pipeline(17) * coeff18;
        product18 <= mul_temp_15(28 DOWNTO 0);
        mul_temp_16 <= delay_pipeline(16) * coeff17;
        product17 <= mul_temp_16(28 DOWNTO 0);
        mul_temp_17 <= delay_pipeline(15) * coeff16;
        product16 <= mul_temp_17(28 DOWNTO 0);
        mul_temp_18 <= delay_pipeline(14) * coeff15;
        product15 <= mul_temp_18(28 DOWNTO 0);
        mul_temp_19 <= delay_pipeline(13) * coeff14;
        product14 <= mul_temp_19(28 DOWNTO 0);
        mul_temp_20 <= delay_pipeline(12) * coeff13;
        product13 <= mul_temp_20(28 DOWNTO 0);
        mul_temp_21 <= delay_pipeline(11) * coeff12;
        product12 <= mul_temp_21(28 DOWNTO 0);
        mul_temp_22 <= delay_pipeline(10) * coeff11;
        product11 <= mul_temp_22(28 DOWNTO 0);
        mul_temp_23 <= delay_pipeline(9) * coeff10;
        product10 <= mul_temp_23(28 DOWNTO 0);
        mul_temp_24 <= delay_pipeline(8) * coeff9;
        product9 <= mul_temp_24(28 DOWNTO 0);
        mul_temp_25 <= delay_pipeline(7) * coeff8;
        product8 <= mul_temp_25(28 DOWNTO 0);
        mul_temp_26 <= delay_pipeline(6) * coeff7;
        product7 <= mul_temp_26(28 DOWNTO 0);
        mul_temp_27 <= delay_pipeline(5) * coeff6;
        product6 <= mul_temp_27(28 DOWNTO 0);
        mul_temp_28 <= delay_pipeline(4) * coeff5;
        product5 <= mul_temp_28(28 DOWNTO 0);
        mul_temp_29 <= delay_pipeline(3) * coeff4;
        product4 <= mul_temp_29(28 DOWNTO 0);
        mul_temp_30 <= delay_pipeline(2) * coeff3;
        product3 <= mul_temp_30(28 DOWNTO 0);
        mul_temp_31 <= delay_pipeline(1) * coeff2;
        product2 <= mul_temp_31(28 DOWNTO 0);
        mul_temp_32 <= delay_pipeline(0) * coeff1;
        product1 <= mul_temp_32(28 DOWNTO 0);

        sum1_1 <= resize(product33, 30) + resize(product32, 30);
        sum1_2 <= resize(product31, 30) + resize(product30, 30);
        sum1_3 <= resize(product29, 30) + resize(product28, 30);
        sum1_4 <= resize(product27, 30) + resize(product26, 30);
        sum1_5 <= resize(product25, 30) + resize(product24, 30);
        sum1_6 <= resize(product23, 30) + resize(product22, 30);
        sum1_7 <= resize(product21, 30) + resize(product20, 30);
        sum1_8 <= resize(product19, 30) + resize(product18, 30);
        sum1_9 <= resize(product17, 30) + resize(product16, 30);
        sum1_10 <= resize(product15, 30) + resize(product14, 30);
        sum1_11 <= resize(product13, 30) + resize(product12, 30);
        sum1_12 <= resize(product11, 30) + resize(product10, 30);
        sum1_13 <= resize(product9, 30) + resize(product8, 30);
        sum1_14 <= resize(product7, 30) + resize(product6, 30);
        sum1_15 <= resize(product5, 30) + resize(product4, 30);
        sum1_16 <= resize(product3, 30) + resize(product2, 30);

        sumpipe1_1 <= sum1_1;
        sumpipe1_2 <= sum1_2;
        sumpipe1_3 <= sum1_3;
        sumpipe1_4 <= sum1_4;
        sumpipe1_5 <= sum1_5;
        sumpipe1_6 <= sum1_6;
        sumpipe1_7 <= sum1_7;
        sumpipe1_8 <= sum1_8;
        sumpipe1_9 <= sum1_9;
        sumpipe1_10 <= sum1_10;
        sumpipe1_11 <= sum1_11;
        sumpipe1_12 <= sum1_12;
        sumpipe1_13 <= sum1_13;
        sumpipe1_14 <= sum1_14;
        sumpipe1_15 <= sum1_15;
        sumpipe1_16 <= sum1_16;
        sumpipe1_17 <= product1;

        add_temp <= resize(sumpipe1_1, 31) + resize(sumpipe1_2, 31);
        sum2_1 <= add_temp(29 DOWNTO 0);
        add_temp_1 <= resize(sumpipe1_3, 31) + resize(sumpipe1_4, 31);
        sum2_2 <= add_temp_1(29 DOWNTO 0);
        add_temp_2 <= resize(sumpipe1_5, 31) + resize(sumpipe1_6, 31);
        sum2_3 <= add_temp_2(29 DOWNTO 0);
        add_temp_3 <= resize(sumpipe1_7, 31) + resize(sumpipe1_8, 31);
        sum2_4 <= add_temp_3(29 DOWNTO 0);
        add_temp_4 <= resize(sumpipe1_9, 31) + resize(sumpipe1_10, 31);
        sum2_5 <= add_temp_4(29 DOWNTO 0);
        add_temp_5 <= resize(sumpipe1_11, 31) + resize(sumpipe1_12, 31);
        sum2_6 <= add_temp_5(29 DOWNTO 0);
        add_temp_6 <= resize(sumpipe1_13, 31) + resize(sumpipe1_14, 31);
        sum2_7 <= add_temp_6(29 DOWNTO 0);
        add_temp_7 <= resize(sumpipe1_15, 31) + resize(sumpipe1_16, 31);
        sum2_8 <= add_temp_7(29 DOWNTO 0);

        sumpipe2_1 <= sum2_1;
        sumpipe2_2 <= sum2_2;
        sumpipe2_3 <= sum2_3;
        sumpipe2_4 <= sum2_4;
        sumpipe2_5 <= sum2_5;
        sumpipe2_6 <= sum2_6;
        sumpipe2_7 <= sum2_7;
        sumpipe2_8 <= sum2_8;
        sumpipe2_9 <= sumpipe1_17;

        add_temp_8 <= resize(sumpipe2_1, 31) + resize(sumpipe2_2, 31);
        sum3_1 <= add_temp_8(29 DOWNTO 0);
        add_temp_9 <= resize(sumpipe2_3, 31) + resize(sumpipe2_4, 31);
        sum3_2 <= add_temp_9(29 DOWNTO 0);
        add_temp_10 <= resize(sumpipe2_5, 31) + resize(sumpipe2_6, 31);
        sum3_3 <= add_temp_10(29 DOWNTO 0);
        add_temp_11 <= resize(sumpipe2_7, 31) + resize(sumpipe2_8, 31);
        sum3_4 <= add_temp_11(29 DOWNTO 0);

        sumpipe3_1 <= sum3_1;
        sumpipe3_2 <= sum3_2;
        sumpipe3_3 <= sum3_3;
        sumpipe3_4 <= sum3_4;
        sumpipe3_5 <= sumpipe2_9;

        add_temp_12 <= resize(sumpipe3_1, 31) + resize(sumpipe3_2, 31);
        sum4_1 <= add_temp_12(29 DOWNTO 0);
        add_temp_13 <= resize(sumpipe3_3, 31) + resize(sumpipe3_4, 31);
        sum4_2 <= add_temp_13(29 DOWNTO 0);

        sumpipe4_1 <= sum4_1;
        sumpipe4_2 <= sum4_2;
        sumpipe4_3 <= sumpipe3_5;

        add_temp_14 <= resize(sumpipe4_1, 31) + resize(sumpipe4_2, 31);
        sum5_1 <= add_temp_14(29 DOWNTO 0);

        sumpipe5_1 <= sum5_1;
        sumpipe5_2 <= sumpipe4_3;

        add_temp_15 <= resize(sumpipe5_1, 31) + resize(sumpipe5_2, 31);
        sum6_1 <= add_temp_15(29 DOWNTO 0);

        sumpipe6_1 <= sum6_1;

        sum_final <= sumpipe6_1;
        output_typeconvert <= sum_final;
        output_register <= output_typeconvert;
        end if;
      end if;
    end process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
