-- -------------------------------------------------------------
--
-- Module: CIC_Filter
-- Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
-- Generated on: 2023-03-14 15:44:01
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- OptimizeForHDL: on
-- TargetDirectory: C:\Users\John\Desktop
-- AddPipelineRegisters: on
-- Name: CIC_Filter
-- TestBenchStimulus: step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure        : Cascaded Integrator-Comb Decimator
-- Decimation Factor       : 128
-- Differential Delay      : 1
-- Number of Sections      : 2
-- Stable                  : Yes
-- Linear Phase            : Yes (Type 1)
--
-- Input                   : s16,15
-- Output                  : s30,15
-- Filter Internals        : Full Precision
--   Integrator Section 1  : s30,15
--   Integrator Section 2  : s30,15
--   Comb Section 1        : s30,15
--   Comb Section 2        : s30,15
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY CIC_Filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(29 DOWNTO 0); -- sfix30_En15
         ce_out                          :   OUT   std_logic  
         );

END CIC_Filter;


----------------------------------------------------------------
--Module Architecture: CIC_Filter
----------------------------------------------------------------
ARCHITECTURE rtl OF CIC_Filter IS
  -- Local Functions
  -- Type Definitions
  -- Constants
  -- Signals
  SIGNAL cur_count                        : unsigned(6 DOWNTO 0); -- ufix7
  SIGNAL phase_1                          : std_logic; -- boolean
  SIGNAL ce_delayline                     : std_logic; -- boolean
  SIGNAL ce_gated                         : std_logic; -- boolean
  SIGNAL ce_out_reg                       : std_logic; -- boolean
  --   
  SIGNAL input_register                   : signed(15 DOWNTO 0); -- sfix16_En15
  --   -- Section 1 Signals 
  SIGNAL section_in1                      : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL section_cast1                    : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum1                             : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL section_out1                     : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_cast                         : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_cast_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp                         : signed(30 DOWNTO 0); -- sfix31_En15
  --   -- Section 2 Signals 
  SIGNAL section_in2                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sum2                             : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL section_out2                     : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_cast_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_cast_3                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL add_temp_1                       : signed(30 DOWNTO 0); -- sfix31_En15
  --   -- Section 3 Signals 
  SIGNAL section_in3                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL diff1                            : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL section_out3                     : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sub_cast                         : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sub_cast_1                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sub_temp                         : signed(30 DOWNTO 0); -- sfix31_En15
  SIGNAL cic_pipeline3                    : signed(29 DOWNTO 0); -- sfix30_En15
  --   -- Section 4 Signals 
  SIGNAL section_in4                      : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL diff2                            : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL section_out4                     : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sub_cast_2                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sub_cast_3                       : signed(29 DOWNTO 0); -- sfix30_En15
  SIGNAL sub_temp_1                       : signed(30 DOWNTO 0); -- sfix31_En15
  --   
  SIGNAL output_register                  : signed(29 DOWNTO 0); -- sfix30_En15


BEGIN

  -- Block Statements
  --   ------------------ CE Output Generation ------------------

  ce_output : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(0, 7);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count >= to_unsigned(127, 7) THEN
          cur_count <= to_unsigned(0, 7);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 7);
        END IF;
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_1 <= '1' WHEN cur_count = to_unsigned(1, 7) AND clk_enable = '1' ELSE '0';

  ce_delay : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ce_delayline <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        ce_delayline <= clk_enable;
      END IF;
    END IF;
  END PROCESS ce_delay;
  ce_gated <=  ce_delayline AND phase_1;

  --   ------------------ CE Output Register ------------------

  ce_output_register : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ce_out_reg <= '0';
    ELSIF clk'event AND clk = '1' THEN
      ce_out_reg <= ce_gated;
      
    END IF; 
  END PROCESS ce_output_register;

  --   ------------------ Input Register ------------------

  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  --   ------------------ Section # 1 : Integrator ------------------

  section_in1 <= input_register;

  section_cast1 <= resize(section_in1, 30);

  add_cast <= section_cast1;
  add_cast_1 <= section_out1;
  add_temp <= resize(add_cast, 31) + resize(add_cast_1, 31);
  sum1 <= add_temp(29 DOWNTO 0);

  integrator_delay_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out1 <= sum1;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section1;

  --   ------------------ Section # 2 : Integrator ------------------

  section_in2 <= section_out1;

  add_cast_2 <= section_in2;
  add_cast_3 <= section_out2;
  add_temp_1 <= resize(add_cast_2, 31) + resize(add_cast_3, 31);
  sum2 <= add_temp_1(29 DOWNTO 0);

  integrator_delay_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out2 <= sum2;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section2;

  --   ------------------ Section # 3 : Comb ------------------

  section_in3 <= section_out2;

  sub_cast <= section_in3;
  sub_cast_1 <= diff1;
  sub_temp <= resize(sub_cast, 31) - resize(sub_cast_1, 31);
  section_out3 <= sub_temp(29 DOWNTO 0);

  comb_delay_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        diff1 <= section_in3;
      END IF;
    END IF; 
  END PROCESS comb_delay_section3;

  cic_pipeline_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cic_pipeline3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        cic_pipeline3 <= section_out3;
      END IF;
    END IF; 
  END PROCESS cic_pipeline_process_section3;

  --   ------------------ Section # 4 : Comb ------------------

  section_in4 <= cic_pipeline3;

  sub_cast_2 <= section_in4;
  sub_cast_3 <= diff2;
  sub_temp_1 <= resize(sub_cast_2, 31) - resize(sub_cast_3, 31);
  section_out4 <= sub_temp_1(29 DOWNTO 0);

  comb_delay_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        diff2 <= section_in4;
      END IF;
    END IF; 
  END PROCESS comb_delay_section4;

  --   ------------------ Output Register ------------------

  output_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_1 = '1' THEN
        output_register <= section_out4;
      END IF;
    END IF; 
  END PROCESS output_reg_process;

  -- Assignment Statements
  ce_out <= ce_out_reg;
  filter_out <= std_logic_vector(output_register);
END rtl;
