# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# Block Designs: bd/Differental_Phasemeter/Differental_Phasemeter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter || ORIG_REF_NAME==Differental_Phasemeter} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axis_red_pitaya_adc_0_0/Differental_Phasemeter_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==Differental_Phasemeter_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axis_constant_0_0/Differental_Phasemeter_axis_constant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axis_constant_0_0 || ORIG_REF_NAME==Differental_Phasemeter_axis_constant_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_clk_wiz_0_0/Differental_Phasemeter_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_clk_wiz_0_0 || ORIG_REF_NAME==Differental_Phasemeter_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axis_red_pitaya_dac_1_0/Differental_Phasemeter_axis_red_pitaya_dac_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axis_red_pitaya_dac_1_0 || ORIG_REF_NAME==Differental_Phasemeter_axis_red_pitaya_dac_1_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axis_broadcaster_0_0/Differental_Phasemeter_axis_broadcaster_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axis_broadcaster_0_0 || ORIG_REF_NAME==Differental_Phasemeter_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_Ki_0/Differental_Phasemeter_GPIO_Ki_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_Ki_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_Ki_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_Kp_0/Differental_Phasemeter_GPIO_Kp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_Kp_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_Kp_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_PLL_GUESS_Freq_0/Differental_Phasemeter_GPIO_PLL_GUESS_Freq_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_PLL_GUESS_Freq_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_PLL_GUESS_Freq_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_FreqMeasure_0/Differental_Phasemeter_GPIO_FreqMeasure_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_FreqMeasure_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_FreqMeasure_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_Integrator_Reset_0/Differental_Phasemeter_GPIO_Integrator_Reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_Integrator_Reset_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_Integrator_Reset_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_Integrator_Reset_1/Differental_Phasemeter_GPIO_Integrator_Reset_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_Integrator_Reset_1 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_Integrator_Reset_1} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_Integrator_Reset1_0/Differental_Phasemeter_GPIO_Integrator_Reset1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_Integrator_Reset1_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_Integrator_Reset1_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_FIFO_Status_0/Differental_Phasemeter_GPIO_FIFO_Status_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_FIFO_Status_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_FIFO_Status_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_FreqMeasureA_0/Differental_Phasemeter_GPIO_FreqMeasureA_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_GPIO_FreqMeasureA_0 || ORIG_REF_NAME==Differental_Phasemeter_GPIO_FreqMeasureA_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_processing_system7_0_0/Differental_Phasemeter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_processing_system7_0_0 || ORIG_REF_NAME==Differental_Phasemeter_processing_system7_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_proc_sys_reset_0_0/Differental_Phasemeter_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_proc_sys_reset_0_0 || ORIG_REF_NAME==Differental_Phasemeter_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_xbar_0/Differental_Phasemeter_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_xbar_0 || ORIG_REF_NAME==Differental_Phasemeter_xbar_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axi_interconnect_1_0/Differental_Phasemeter_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axi_interconnect_1_0 || ORIG_REF_NAME==Differental_Phasemeter_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axi_dma_0_1/Differental_Phasemeter_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axi_dma_0_1 || ORIG_REF_NAME==Differental_Phasemeter_axi_dma_0_1} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axi_protocol_convert_0_1/Differental_Phasemeter_axi_protocol_convert_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axi_protocol_convert_0_1 || ORIG_REF_NAME==Differental_Phasemeter_axi_protocol_convert_0_1} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axi_interconnect_2_1/Differental_Phasemeter_axi_interconnect_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axi_interconnect_2_1 || ORIG_REF_NAME==Differental_Phasemeter_axi_interconnect_2_1} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_xbar_3/Differental_Phasemeter_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_xbar_3 || ORIG_REF_NAME==Differental_Phasemeter_xbar_3} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axi_interconnect_0_2/Differental_Phasemeter_axi_interconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axi_interconnect_0_2 || ORIG_REF_NAME==Differental_Phasemeter_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axi_interconnect_0_3/Differental_Phasemeter_axi_interconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axi_interconnect_0_3 || ORIG_REF_NAME==Differental_Phasemeter_axi_interconnect_0_3} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_axis_data_fifo_0_0/Differental_Phasemeter_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_axis_data_fifo_0_0 || ORIG_REF_NAME==Differental_Phasemeter_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_AXI4_Stream_Writer_0_0/Differental_Phasemeter_AXI4_Stream_Writer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_AXI4_Stream_Writer_0_0 || ORIG_REF_NAME==Differental_Phasemeter_AXI4_Stream_Writer_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_Phase_Locked_Loop_0_0/Differental_Phasemeter_Phase_Locked_Loop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_Phase_Locked_Loop_0_0 || ORIG_REF_NAME==Differental_Phasemeter_Phase_Locked_Loop_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_Phase_Locked_Loop_0_1/Differental_Phasemeter_Phase_Locked_Loop_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_Phase_Locked_Loop_0_1 || ORIG_REF_NAME==Differental_Phasemeter_Phase_Locked_Loop_0_1} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_Reset_Latch_0_0/Differental_Phasemeter_Reset_Latch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_Reset_Latch_0_0 || ORIG_REF_NAME==Differental_Phasemeter_Reset_Latch_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_Subtractor_0_0/Differental_Phasemeter_Subtractor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_Subtractor_0_0 || ORIG_REF_NAME==Differental_Phasemeter_Subtractor_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_DAC_Router_0_0/Differental_Phasemeter_DAC_Router_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_DAC_Router_0_0 || ORIG_REF_NAME==Differental_Phasemeter_DAC_Router_0_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_auto_pc_0/Differental_Phasemeter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_auto_pc_0 || ORIG_REF_NAME==Differental_Phasemeter_auto_pc_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_s00_mmu_0/Differental_Phasemeter_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_s00_mmu_0 || ORIG_REF_NAME==Differental_Phasemeter_s00_mmu_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_auto_us_0/Differental_Phasemeter_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_auto_us_0 || ORIG_REF_NAME==Differental_Phasemeter_auto_us_0} -quiet] -quiet

# IP: bd/Differental_Phasemeter/ip/Differental_Phasemeter_auto_pc_1/Differental_Phasemeter_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Differental_Phasemeter_auto_pc_1 || ORIG_REF_NAME==Differental_Phasemeter_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/Differental_Phasemeter_ooc.xdc
