# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_NCO_0_0/system_NCO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_NCO_0_0 || ORIG_REF_NAME==system_NCO_0_0} -quiet] -quiet

# IP: bd/system/ip/system_FIR_Filter_1_0_0/system_FIR_Filter_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_FIR_Filter_1_0_0 || ORIG_REF_NAME==system_FIR_Filter_1_0_0} -quiet] -quiet

# IP: bd/system/ip/system_NCO_1_0/system_NCO_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_NCO_1_0 || ORIG_REF_NAME==system_NCO_1_0} -quiet] -quiet

# IP: bd/system/ip/system_Mixer_0_0/system_Mixer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Mixer_0_0 || ORIG_REF_NAME==system_Mixer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ConstantIP_0_0/system_ConstantIP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ConstantIP_0_0 || ORIG_REF_NAME==system_ConstantIP_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ConstantIP_1_0/system_ConstantIP_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ConstantIP_1_0 || ORIG_REF_NAME==system_ConstantIP_1_0} -quiet] -quiet

# IP: bd/system/ip/system_ConstantIP_2_0/system_ConstantIP_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ConstantIP_2_0 || ORIG_REF_NAME==system_ConstantIP_2_0} -quiet] -quiet

# IP: bd/system/ip/system_ConstantIP_3_0/system_ConstantIP_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ConstantIP_3_0 || ORIG_REF_NAME==system_ConstantIP_3_0} -quiet] -quiet

# IP: bd/system/ip/system_ConstantIP_4_0/system_ConstantIP_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ConstantIP_4_0 || ORIG_REF_NAME==system_ConstantIP_4_0} -quiet] -quiet

# IP: bd/system/ip/system_Compressor_0_0/system_Compressor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Compressor_0_0 || ORIG_REF_NAME==system_Compressor_0_0} -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/Zynq_Testing/Zynq_Testing.gen/sources_1/bd/system/system_ooc.xdc
