# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.srcs/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0.xci
# IP: The module: 'Differental_Phasemeter_GPIO_KpB_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Differental_Phasemeter_GPIO_KpB_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Differental_Phasemeter_GPIO_KpB_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Differental_Phasemeter_GPIO_KpB_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.srcs/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0.xci
# IP: The module: 'Differental_Phasemeter_GPIO_KpB_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Differental_Phasemeter_GPIO_KpB_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Differental_Phasemeter_GPIO_KpB_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/Differental_Phasemeter/ip/Differental_Phasemeter_GPIO_KpB_0/Differental_Phasemeter_GPIO_KpB_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Differental_Phasemeter_GPIO_KpB_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
