# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.srcs/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0.xci
# IP: The module: 'system_Delay_Amount_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Delay_Amount_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Delay_Amount_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Delay_Amount_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.srcs/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0.xci
# IP: The module: 'system_Delay_Amount_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Delay_Amount_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Delay_Amount_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/John/Desktop/Honours_Project/RP-Production/RP-Production.gen/sources_1/bd/system/ip/system_Delay_Amount_0/system_Delay_Amount_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Delay_Amount_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
